### ISSUE TITLE
Neo 0.8.0

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#13]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=669892887

**Comment by s4safeld** [comment]
I Changed the IO-Formats and the Funders according to Adam Davisons comments.
At "Funders" Davison wrote that there are many more Funders than CNRS and HBP.
At the bottom of this list https://neo.readthedocs.io/en/latest/authors.html a few institutions can be found which contributed neo. Should i find out the funders of each of these institutions or is HBP and CNRS enough?

**Comment by FeldNico** [comment]
Added TODO to remove .* from the Input Formats, as it stands for any possible format.
The components should be integrated in the KG, but NEO should be a component of these, not the other way around, as it is right now. Or was is discussed otherwise?

**Comment by s4safeld** [comment]
processed TODO and removed softwares from components list

**Comment by FeldNico** [comment]
I will talk to Andrew on the Summit

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer added feedback in the spreadsheet. Please check and if there are no further questions please integrate.

**Comment by s4safeld** [comment]
finished integrating neo 0.8.0. 
Before i add my spreadsheet to the final spreadheets i will try to research as much author email adresses as possible. But since thats not important for the integration right know, I will set this to "to be released"
