### ISSUE TITLE
Neuromorphic Platform Python client 0.8.2

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#139]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=104169998

**Comment by jagru20** [comment]
Contacted @dguarino for revision.

**Comment by jagru20** [comment]
please integrate.

**Comment by jagru20** [comment]
released.
