### ISSUE TITLE
Neo-Viewer 1.0.0

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#15]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=1477639131

**Comment by s4safeld** [comment]
Changed IO-Formats and Summary according to Adam Davisons comments. Additionally I corrected the name of one of the authors which it seems I've gotten from the wrong source

**Comment by FeldNico** [comment]
Added TODO to remove .* from Input Formats
After that, please integrate

**Comment by s4safeld** [comment]
removed .* format, will integrate soon

**Comment by s4safeld** [comment]
I finished integrating the software as far as possible. "Authors", "Copyright holders" and "Funders" still can't be edited in the current development stage. But besides from that, the Software is completely finished.

**Comment by FeldNico** [comment]
Please check the integration in the Editor. For example the description was missing and the name was not consitent in the spreadsheet and the editor (Uppercase/Lowercase). please comment and change label when finished

**Comment by s4safeld** [comment]
Added missing description, changed the name to Upper Case letters and added "none" to citation to not let the field be empty.

**Comment by FeldNico** [comment]
released
