### ISSUE TITLE
NeuroM 1.4.15

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#150]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=997387160

**Comment by s4safeld** [comment]
This Software is already pursued by @AnnHa2019, #53

**Comment by bweyers** [comment]
OK, I will then close this issue!
