### ISSUE TITLE
Connectomic Composition Predictor

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#16]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=1893144003

**Comment by FeldNico** [comment]
Initial Email to Developer: 06.01.20

**Comment by FeldNico** [comment]
Reminder Email: 21.01.20

**Comment by s4safeld** [comment]
We have to check if and/or how Jupyter Notebook is implemented as a programming language. Technically it is more like a developing tool for working with various programming languages (mainly Python).
Github classifies it as a programming language, I would be ok with both (keeping or leaving) but someone has to decide.

**Comment by s4safeld** [comment]
I scrolled through the descriptions of the individual functions in the documentation, and found some more information about the input-output formats. I added them into the spreadsheet and the KG.

**Comment by s4safeld** [comment]
finished integrating CCP
