### ISSUE TITLE
Test Olivier 1.0.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#160]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=1357747354

**Comment by herr-zett** [comment]
This seems to be an instance to test the software catalog in the Collaboratory?

**Comment by bweyers** [comment]
Seems to be just a placeholder for testing the original catalogue.
