### ISSUE TITLE
MeshView 0.9

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#167]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=1121785851

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1203380408

**Comment by herr-zett** [comment]
The software isn't documented that well. It could very well be the case, that the version number might have changed.
The original version of this web-application uses Flash, whereas a newer version makes use of WebGL. On the homepage it is stated that the WebGL version is still a work in progress.

**Comment by bweyers** [comment]
@herr-zett Thanks for the hint. I guess you mentioned that also in the spreadsheet? As these seem to be questions answered by the developer.

**Comment by herr-zett** [comment]
> @herr-zett Thanks for the hint. I guess you mentioned that also in the spreadsheet? As these seem to be questions answered by the developer.

I've added a corresponding question within the row regarding the version number.

**Comment by jagru20** [comment]
Reminder sent

**Comment by jagru20** [comment]
has been released
