### ISSUE TITLE
SynapseGenerator 0.9+5

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#169]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=939360933

**Comment by AnnHa2019** [comment]
There is no source code and only a link to the documentation and the short collab entry. For me the project looks outdated.

**Comment by jagru20** [comment]
contacted developers

**Comment by jagru20** [comment]
Closed due to insufficient information and irresponsive contact persons.
