### ISSUE TITLE
Arbor v0.2.2

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#17]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1118569048

**Comment by FeldNico** [comment]
Please add link to the spreadsheet-tab in the description.

**Comment by FeldNico** [comment]
Ready to be integrated

**Comment by FeldNico** [comment]
Released
