### ISSUE TITLE
VTK-m 1.5.0

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#18]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=209520682

**Comment by FeldNico** [comment]
Please add link to the spreadsheet-tab in the description.

**Comment by FeldNico** [comment]
Developer not responding. Please integrate as it is right now.

**Comment by FeldNico** [comment]
Released
