### ISSUE TITLE
Brion 3.2.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#188]
[](https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=1275918232)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1380644456

**Comment by jagru20** [comment]
Developer left feedback, please integrate.

**Comment by herr-zett** [comment]
Regarding the Data Types the developer suggested "matrix based data types for spike/compartment reports and circuits". How do we map this onto our list of Data Types? Are we in need of a new category?

Moreover the developer indicated the following:
<blockquote>
Brion is in maintenance mode only. It will be replaced as soon as possible with other libraries. There is no active support and all the updates are focused on maintenance while it is being replaced
</blockquote>

Does this affect our process of integration?

**Comment by herr-zett** [comment]
I've already created a KG-entry with the available and curated information. The KG-entry has to be updated if the Data Types will change

**Comment by bweyers** [comment]
@herr-zett please add new data type (Matrix Date Type) and finalize integration.

**Comment by jagru20** [comment]
released
