### ISSUE TITLE
PLIViewer v1.2.0

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#19]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=689753877

**Comment by FeldNico** [comment]
Please add link to the spreadsheet-tab in the description.

**Comment by FeldNico** [comment]
Initial Email to Developer: 06.01.20

**Comment by FeldNico** [comment]
Developer filled out the spreadsheet and proposed to integrate Version 1.2.0. Please update corresponding fields and check links.

**Comment by herr-zett** [comment]
Author has already updated corresponding fields by himself. Software ready for integration

**Comment by FeldNico** [comment]
Please integrate

**Comment by FeldNico** [comment]
Released
