### ISSUE TITLE
Neurorobotics Experiment Simulation Viewer 0.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#197]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=517461529

**Comment by FeldNico** [comment]
This software will be integrated but not curated, as it was not updated in SGA2

**Comment by jagru20** [comment]
replaced by #415
