### ISSUE TITLE
Compatibility with HBP Software Catalogue and Knowledge Graph

### ISSUE THREAD

**Issue by bweyers** [bweyers/HBPVisCatalogue#2]
Es ist wichtig sehr frühzeitig im Entwicklungsprozess des Vis Catalogues die Kompatibilität des Metadatenschemas mit der Struktur des Software Catalogues und des Knowledge graphs zu überprüfen/zu ermöglichen. 

TODO: 
- Wie sind die Metadaten für den SW Katalog organisiert und gespeichert?
- Wie sind die Ontologien im Knoweldege Graph hinterlegt? Es ist nicht OWL, aber wie sieht das Format aus und wie sieht eine mögliche Transformation aus? Kann man die Entwickler dazu bewegen auch OWL kompatibel zu sein?

**Comment by flangel3** [comment]
Ontologien im Knowledge Graph: In https://collab.humanbrainproject.eu/#/collab/1176/nav/10349 wird sowohl Knowledge-Space.org als auch "Ontology Service API" als verwendete Ontology Services erwähnt. Erstere ist unter https://github.com/OpenKnowledgeSpace/KnowledgeSpace einsehbar. Habe ich aber noch nicht genauer gemacht.

Allerdings sind verweise auf die Ontology API des Knowledge Graphs in der Doku als deprecated markiert und nicht mehr einsehbar, eventuell wurde da was geändert. Soll ich versuchen Kontakt mit jemandem aufzunehmen oder hast du schon einen Kontakt aus dem Entwicklerteam? Informationen wie die Metadaten im SW Katalog organisiert sind konnte ich leider nicht finden.

**Comment by bweyers** [comment]
Next steps: 
1. Meeting mit Koratorenteam in Jülich
2. Meeting mit SW Catalogue developer für die Integrationsplanung
  a) Welche Ontologien werden genutzt (OWL is ok)
  b) Wie sehen die Metadatan für den SW Catalogue aus?
