### ISSUE TITLE
NEST v2.20.0

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#20]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=472311509

**Comment by FeldNico** [comment]
Please add link to the spreadsheet-tab in the description.

**Comment by FeldNico** [comment]
Added 2 TODOs

**Comment by herr-zett** [comment]
Processed TODOs

**Comment by FeldNico** [comment]
Initial Email to Developer: 07.01.20

**Comment by FeldNico** [comment]
Reminder Email: 21.01.20

**Comment by FeldNico** [comment]
Version change to v2.20.0

**Comment by FeldNico** [comment]
Author edited the spreadsheet and this software will be integrated & released by me to be ready for the summit

**Comment by FeldNico** [comment]
Released
