### ISSUE TITLE
MSPViz v0.2.6

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#21]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1389726744

**Comment by herr-zett** [comment]
Does the copyright signature on the bottom of this [website](https://gmrv.es/gmrvvis/mspviz/) refer to the software or to the website itself?

**Comment by bweyers** [comment]
I guess it is refering to the website's copyright...

**Comment by FeldNico** [comment]
Please add link to the spreadsheet-tab in the description.

**Comment by herr-zett** [comment]
Do all contributors listed in the GitHub repository have to be mentioned as authors of the software? One of those three contributors didn't provide his/her real name

**Comment by FeldNico** [comment]
Added 2 TODOS

**Comment by herr-zett** [comment]
Processed TODOs

**Comment by FeldNico** [comment]
Initial Email to Developer: 07.01.20

**Comment by FeldNico** [comment]
@bweyers This is your software :/ This is a kind reminder to send us feedback :(

**Comment by FeldNico** [comment]
This must be send to:
Juan Pedro Brito <juanpedro.brito@upm.es>
Pablo Toharia <pablo.toharia@upm.es>
ASAP

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer provided information. Please check and integrate

**Comment by FeldNico** [comment]
released
