### ISSUE TITLE
CoreNeuron 0.16

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#23]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit?usp=sharing

**Comment by FeldNico** [comment]
Initial Email to Developer: 10.12.19

**Comment by FeldNico** [comment]
Reminder Email: 20.12.19

**Comment by FeldNico** [comment]
> Hello. The metadata is substantially correct but there are several typos that I could not change. Nor enter anything into column D.
The link is now fixed and replied. Waiting for additional answer

**Comment by FeldNico** [comment]
Developer left no additional comments -> Please integrate

**Comment by FeldNico** [comment]
Released
