### ISSUE TITLE
NMODL Framework 0.2

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#24]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=63910651

**Comment by FeldNico** [comment]
Added 2 TODOS

**Comment by AnnHa2019** [comment]
TODOS edited

**Comment by FeldNico** [comment]
Initial Email to Developer: 08.01.20

**Comment by FeldNico** [comment]
Reminder email: 21.01.20
