### ISSUE TITLE
NetPyNe 0.9.4

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#25]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=2032477112

**Comment by FeldNico** [comment]
Added TODOs

**Comment by AnnHa2019** [comment]
Edited TODOs

**Comment by FeldNico** [comment]
Added TODOs

**Comment by AnnHa2019** [comment]
Edited TODOs

**Comment by FeldNico** [comment]
Initial Email to Developer: 21.01.20

**Comment by FeldNico** [comment]
Developer left feedback

**Comment by bweyers** [comment]
Please integrate!

**Comment by bweyers** [comment]
released
