### ISSUE TITLE
NeuroSTR 0.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#254]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=815411116

**Comment by FeldNico** [comment]
This software will be integrated but not curated, as it was not updated in SGA2

**Comment by bmihaljevic** [comment]
I received the following instruction regarding #254 and #316: 

> We have listed these two. Please indicate in the issues (by commenting) which of both should go into the KG and then please fill out the Google Spreadsheets (link in the first comment of the issue) accordingly. 

I suggest that both NeuroSTR and neurostrr go into the KG, as they are two different componentes. If we need to choose one, then choose NeuroSTR (#254). I have filled in the spreadsheets.

**Comment by bweyers** [comment]
developer added information to the spreadsheet @AnnHa2019 You can now continue working on it.

**Comment by jagru20** [comment]
released
