### ISSUE TITLE
Rebuild an existing single cell model 1.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#261]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=1640760705

**Comment by herr-zett** [comment]
This seems to be a copy of #347

**Comment by bweyers** [comment]
@herr-zett yes, seems like a copy and thus can be closed.
