### ISSUE TITLE
Synaptic Events Fitting Notebook 1.3

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#262]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=1522913579

**Comment by s4safeld** [comment]
I can't find much about this software. In fact I only found [this](https://collab.humanbrainproject.eu/#/collab/1655/nav/18580) where Synaptic Events fitting is referred to as a Use case. After some more research i found some kind of [documentation](https://humanbrainproject.github.io/hbp-sp6-guidebook/online_usecases/trace_analysis/syn_events_fit/syn_events_fit.html#synaptic-events-fitting) and something that seems like the software [itself](https://collab.humanbrainproject.eu/#/collab/1655/nav/66850) inside of a [list of use cases](https://collab.humanbrainproject.eu/#/collab/1655/nav/66850). But when I try to create a project to play around with it. I get a bad gateway error.

I filled the spreadsheet a little bit, including with some mail adresses. 
We should discuss the integration of this software. Together with the following: #267 #266 and other Use Cases later to be discovered.

**Comment by bweyers** [comment]
Developer has edited the spreadsheet. As the name has changed, please look for the original entity in the KG and change its name too.

**Comment by FeldNico** [comment]
Editor-entry must be updated

**Comment by AnnHa2019** [comment]
Who is working on this issue?

**Comment by FeldNico** [comment]
@AnnHa2019 This issue is assigned to @PatriziaDuhr

**Comment by bweyers** [comment]
Has been released
