### ISSUE TITLE
Synaptic events fitting (user's data) 1.3

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#267]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=773947779

**Comment by herr-zett** [comment]
This issue was referenced in another issue that is already closed. Should this be closed to?

**Comment by bweyers** [comment]
yes can be closed especially as this issue refers to user's data, which is not topic of what we are doing.
