### ISSUE TITLE
NeuroSuites 1.0

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#27]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=1833953926

**Comment by s4safeld** [comment]
restored the IO-formats i previously deleted

**Comment by FeldNico** [comment]
Added TODO

**Comment by FeldNico** [comment]
Please check again (e.g. programming language)

**Comment by s4safeld** [comment]
The detection of all the programming languages is a bit tricky:
As always there is this "Programming-language-bar"-thing on the top of the gitlab page, but it obviuosly does not display all the languages of neurosuites, since **Python is missing.** 

Inside of a [DOI](https://doi.org/10.1101/2020.02.04.934174) of a **subcomponent** of neurosuites i found [this image](https://www.biorxiv.org/content/biorxiv/early/2020/02/04/2020.02.04.934174/F2.large.jpg?width=800&height=600&carousel=1). 
I cant be sure if the image mentiones **all** the programming languages of neurosuites. 
For now i listed all the languages i could find on given image.

**Comment by s4safeld** [comment]
Apart from that I updated the spreadsheet of neurosuites. There was an update and I found some small missing things. I will set it to "in curation" again

**Comment by s4safeld** [comment]
Oh, and for some reason the gitlab page is mostly talking about v1.1 while the homepage is still in v1.0. There is and there will be a discrepancy of the source code and homepage. But I dont think that thats our problem since the author decided to not use the "releases" feature of gitlab.

**Comment by FeldNico** [comment]
Could you try to find a email adress of the developer?

**Comment by s4safeld** [comment]
Found and added email adress in spreadsheet

**Comment by bweyers** [comment]
04-05-20 sent for revision

**Comment by FeldNico** [comment]
Reminder sent

**Comment by jagru20** [comment]
released
