### ISSUE TITLE
VIOLA - VIsualization Of Layer Activity 10.07.2017

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#274]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=260005378

**Comment by FeldNico** [comment]
This software will be integrated but not curated, as it was not updated in SGA2

**Comment by herr-zett** [comment]
Already integrated.
#34 

Although I'm not sure what the source of the date 10.07.2017 mentioned here is.
The instance I've already integrated has an earlier creation date.

**Comment by bweyers** [comment]
The date is the last date of change in the Collab SW cataloge as no version is document in the collab datalogue. However, as VIOLA already exsits #34 in the KG, this issue will be closed.
