### ISSUE TITLE
SDA: Simulation of Diffusional Association 7.2.4

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#275]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=135766110)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1518783410

**Comment by herr-zett** [comment]
@jagru20 During integration new questions arose:

- The developer added three components. I'm not sure whether these are standalone-software and if so, where they are documented or where the source code can be found.

- The developer added some file formats I'm unsure how to integrate:
  - dx grid data (ASCII or binary)
  - input parameters in ASCII format
  - ASCII data file

**Comment by bweyers** [comment]
@jagru20 could you please check these point that the integration can continue?

**Comment by DKokh** [comment]
SDA is a standalone software and the sorce codes can be download here:  https://www.h-its.org/downloads/sda7/  (need regestration),  
The complete documentation is here:  https://mcm.h-its.org/sda/doc/doc_sda7/doc.html

 This is the real format of the input data , I don't know how to define it differently.... What  kind of the input format would you accept?

**Comment by jagru20** [comment]
Dear Daria,

sorry for the delay in this issue. 
The unclear point about the input files is the file extensions that are to be used. Could you list them? We can go on with integration then.

Kind regards

**Comment by DKokh** [comment]
Format of the input files:

-PDB files  : *.pdb
-Electrostatics and other  grids: *.dx
- file with input parameters - ASCII text  (any extention), see example for more detail
- files with reaction atoms - also ASCII text  (any extention), see example for more detail

Is it ok?

**Comment by bweyers** [comment]
Thanks @DKokh! I think that is all we need. We then list the two ASCII format-based file types with an .txt ending as this seems to be the quasi standard for unformatted ASCII text files. 

@herr-zett please finalize integration!

**Comment by herr-zett** [comment]
@bweyers @jagru20 I've added the file formats into the KG.

However, I'm still unsure how to proceed with the components added in field B25 of the spreadsheet:
* brownian motion simulator
* docking component
* clustering module

By integrating them into the KG they will become software projects that have to be worked on, too. To me they seem rather vague and do not represent specific pieces of software that could be integrated.

**Comment by jagru20** [comment]
@herr-zett These seem to be rather descriptions software features than components. Please continue integration without treating them as separate components.

**Comment by DKokh** [comment]
yes,
brownian motion simulator; docking component;  clustering module  - are features (or modules)  of the SDA software package.

**Comment by jagru20** [comment]
SDA 7.4.2 is now released into the Knowledge Graph.
