### ISSUE TITLE
MIP Microservices-infrastructure 2

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#277]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1006914011

**Comment by FeldNico** [comment]
This software will be integrated but not curated, as it was not updated in SGA2

**Comment by jagru20** [comment]
has been curated in issue #72
