### ISSUE TITLE
QuickNII 2.2

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#28]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=580454972

**Comment by Majpuc** [comment]
I've added some comments.

**Comment by s4safeld** [comment]
I added some missing information provided by Majpuc. She left an interesting comment at "features". Maybe we should discuss that next meeting?

**Comment by FeldNico** [comment]
Added TODOs and answered @Majpuc

**Comment by s4safeld** [comment]
Processed comments by @Majpuc and changed Sheet accordingly

**Comment by FeldNico** [comment]
if no further questions, please integrate

**Comment by s4safeld** [comment]
At Screenshots @Majpuc wrote that she will provide one. So I did not integrate the one in the sheet.
Apart from that I finished integrating software as far as currently possible.

**Comment by FeldNico** [comment]
Released
