### ISSUE TITLE
KappaNEURON 0.3.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#280]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=588660924

**Comment by FeldNico** [comment]
This software will be integrated but not curated, as it was not updated in SGA2

**Comment by AnnHa2019** [comment]
The sheet has been revised. Is the application still up-to-date?

**Comment by jagru20** [comment]
We suppose so.

**Comment by jagru20** [comment]
The developer does not react to our request for revision. The issue is closed and not integrated, as the description is not sufficient. The issue may be reopened on demand.
