### ISSUE TITLE
3DBasalRM: Incomplete basal dendrites repair 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#281]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=128499962)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=203010358

**Comment by jagru20** [comment]
reminder sent

**Comment by jagru20** [comment]
Developer does not react to request for revision. As there are unanswered questions, the metadata will not be published. The issue may be reopened on demand.
