### ISSUE TITLE
ElectroMorpho 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#283]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=1640767282

**Comment by bweyers** [comment]
@AnnHa2019 please specify the actual problem identified with this entry.

**Comment by AnnHa2019** [comment]
The problem was that the last activity was three years ago.

**Comment by jagru20** [comment]
contacted developer to find out if software is still active.

**Comment by AnnHa2019** [comment]
added new mail adress

**Comment by jagru20** [comment]
4th try of getting into touch with developer

**Comment by jagru20** [comment]
This is closed due to insufficient Information and the lack of response when attempting to get into touch with developers.
