### ISSUE TITLE
Neurorobotics Robot Designer 2.0.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#284]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=129239498

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1699434414

**Comment by jagru20** [comment]
replaced by #415
