### ISSUE TITLE
Neurorobotics experiments and models library 2.2

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#287]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1651455082

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=961009333

**Comment by jagru20** [comment]
request for further information sent to Axel von arnim (axel.vonarnim@fortiss.org)

**Comment by jagru20** [comment]
replaced by #415
