### ISSUE TITLE
fairgraph 0.5.1

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#29]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=517870308

**Comment by FeldNico** [comment]
Discuss: How to handle accessibility as a HBP-Account is needed

**Comment by FeldNico** [comment]
Added TODO

**Comment by s4safeld** [comment]
removed "Python 3" in "Components"

**Comment by FeldNico** [comment]
HBP Account into softwarerequirements

**Comment by s4safeld** [comment]
done

**Comment by s4safeld** [comment]
Maybe add something like "Metadata Types" to Feature list? Since this software is working with the Metadata from the KG

**Comment by bweyers** [comment]
That is quite a good idea and we added it to the list of features.

**Comment by FeldNico** [comment]
Developer will be notified soon

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer added feedback in the spreadsheet. Please check and if there are no further questions please integrate.

**Comment by s4safeld** [comment]
The Developer didn't give an answer to the question asked at 'device'. What shall i do?

**Comment by s4safeld** [comment]
At components there are the following two listed: Knowledge Graph and Nexus Query API.
Nexus Query API is also a Component of the Knowledge Graph. Last meeting we discussed [this](https://github.com/bweyers/HBPVisCatalogue/issues/69#issuecomment-586237320) comment and decided that we wont implement the components of the KG as it is to complicated and minor for our goals. 
I guess I will then delete Nexus Query API from the Components of fairgraph as well?

**Comment by s4safeld** [comment]
I finished integrating fairgraph. The unclear points mentioned above were handled in my personal discretion and need to be validated.

**Comment by FeldNico** [comment]
Looks good. Please update spreadsheet according to the integrated meta data
