### ISSUE TITLE
NSuite 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#290]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=721360128)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1284162710

**Comment by jagru20** [comment]
developer left feedback, please integrate

**Comment by jagru20** [comment]
Has been released
