### ISSUE TITLE
Model Validation Framework REST API 1.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#294]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1578454550

**Comment by bweyers** [comment]
@apdavison 
Hi Andrew, 
we are currently looking into this software and are wondering whether the REST API needs an individual entry in the knowledge graph considering the model validation framework is currently in curation? See here: #351

**Comment by apdavison** [comment]
The Model Validation Framework is an umbrella project, which includes:
- the REST API
- the Model Catalog web client
- a Python client
- a collection of Python libraries based on SciUnit

I think it's probably better to represent each component individually. I'm not sure there's any need to represent the umbrella in the KG.
