### ISSUE TITLE
Nutil 0.33

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#30]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=1569430752

**Comment by Majpuc** [comment]
I added some comments

**Comment by s4safeld** [comment]
I added some missing information provided by Majpuc

**Comment by FeldNico** [comment]
Wait for @Majpuc to check for linux

**Comment by Majpuc** [comment]
Yes, sorry. The actual sw runs on Windows only but can be wrapped to run on Linux. So I guess you can put Windows for now and we will see for the future versions. Thanks!

**Comment by FeldNico** [comment]
@Majpuc Thanks! We will do
@s4safeld Please change the OS to Windows only and then please integrate it

**Comment by s4safeld** [comment]
Finished intergrating Nutil as far as currently possible

**Comment by FeldNico** [comment]
Released
