### ISSUE TITLE
eFELunit 1.1.5

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#301]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1863551279

**Comment by AnnHa2019** [comment]
Little information available

**Comment by appukuttan-shailesh** [comment]
Added info. Looks fine.
Let me know if anything else required.

Note: component (and tab in spreadsheet) renamed to 'eFELunit 1.1.5'.... corresponding to PyPI release version

**Comment by jagru20** [comment]
https://kg.ebrains.eu/search/instances/Software/e80b83f8-f6e7-46f1-aaaf-b795c4388b0e
