### ISSUE TITLE
3DBasalMS: basal arborization reconstruction and simulation 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#306]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1950139530

**Comment by jagru20** [comment]
reminder sent

**Comment by jagru20** [comment]
Developer does not react to request for revision. As there are unanswered questions, the metadata will not be published. The issue may be reopened on demand.
