### ISSUE TITLE
MorphoUnit 1.0.4

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#309]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1960509592

**Comment by jagru20** [comment]
Reminder sent

**Comment by appukuttan-shailesh** [comment]
Added info. Looks fine.
Let me know if anything else required.

**Comment by jagru20** [comment]
Released.

**Comment by jagru20** [comment]
Unreleased again... @PatriziaDuhr, please check to what extent the developer's feedback differs from that already integrated and update it, thanks!

**Comment by jagru20** [comment]
released
