### ISSUE TITLE
The Jupyter Notebook 6.0.2

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#31]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=59661695

**Comment by FeldNico** [comment]
One TODO. After that please integrate

**Comment by s4safeld** [comment]
I finished integrating the software as far as currently possible

**Comment by FeldNico** [comment]
Released
