### ISSUE TITLE
Bids Manager & Pipeline 0.2.5

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#310]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=292798506

**Comment by AnnHa2019** [comment]
Question: Are we talking about BIDS 
https://bids.neuroimaging.io/acknowledgements.html

or is it about a special extension?
https://collab.humanbrainproject.eu/#/collab/19/nav/2108?state=software,Bids-Manager

**Comment by jagru20** [comment]
The developer does not react to our request for revision. As the information seems to be quite comprehensive, I suggest continuing with integration.

**Comment by jagru20** [comment]
contacted developer for information about 4D neuroimaging input format. If there is no response within a week, I suggest closing this issue.

**Comment by jagru20** [comment]
released.
