### ISSUE TITLE
The fast and parallel Virtual Brain 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#311]
Original:
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=649760

Edited:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1374274706

**Comment by BrainModes** [comment]
Fields updated.

**Comment by bweyers** [comment]
@herr-zett Please check for completness and potential extensions needed. Author added information.

**Comment by herr-zett** [comment]
I've created a new spreadsheet with additional information. The original one filled out by the developer remained unaltered.

**Comment by BrainModes** [comment]
Dear Benni, dear all, I noted that TVB-NEST, TVB-App and TVB Atlas have been released. Thanks a lot! :-) Not yet released are presently Fast-TVB and TVB-processing-pipeline it seems to me. If these two could also get released before EC review starting in 10 days, it would be much appreciated. Many thanks for your support. Petra

**Comment by bweyers** [comment]
@BrainModes Thanks! This seems to be possible. 
@herr-zett Please integrate!

**Comment by jagru20** [comment]
released
