### ISSUE TITLE
NEST YAML Platform (NYP) 0.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#313]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=483381313

**Comment by AnnHa2019** [comment]
Last activity two years ago

**Comment by jagru20** [comment]
Dear @andresni, 

we are currently in the process of integrating software metadata into the Human Brain Project's Knowledge Graph. We also encountered your Software and found that the last activity on this project was about two years ago. Is the NEST YAML Platform still under development or is this an abandoned project? Thank you for your answer. 

Kind regards,

Jan Gründling

**Comment by jagru20** [comment]
Dear @andresni, could you please comment? Otherwise we will close this issue as we assume there is no curation needed.

**Comment by andresni** [comment]
Hi Jan,
Sorry for lack of reply. It drowned in my email it appears.

The YAML platform was under development, but was supplanted by another very
similar effort from the US at which point we felt no real need to continue
working on it. In other words, it's in one sense abandonded, but it still
works and is "useful" but continously less and less so as the other project
has a wider scope than we did.
Best,
André S. Nilsen

**Comment by jagru20** [comment]
Thank you for this information. What is the exact name of the other tool?

**Comment by andresni** [comment]
They call it deNEST
See Git repository here: https://github.com/TomBugnon/deNEST

**Comment by jagru20** [comment]
Thanks! @AnnHa2019 I suggest to curate deNest instead of NEST YAML then. Please start a new curation process, hence this issue will be closed.
