### ISSUE TITLE
ViSimpl 0.1.3

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#314]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=657331716)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=553519755

**Comment by jagru20** [comment]
@herr-zett is there no more information available? What about [this manual](http://gmrv.es/gmrvvis/apps/visimpl/doc/gmrvis_Applications_User_Manuals.pdf)? Please check for further info.

**Comment by herr-zett** [comment]
@jagru20 Sorry, I forgot to include the link to the spreadsheet that was edited by me. I will add it to the original comment, that opened this issue

**Comment by jagru20** [comment]
The description has been extended significantly and the spreadsheet revised by the developer. Thus I suggest continuing integration.

**Comment by jagru20** [comment]
Released
