### ISSUE TITLE
neurostr 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#316]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1696653326

**Comment by bmihaljevic** [comment]
I received the following instruction regarding #254 and #316:

> We have listed these two. Please indicate in the issues (by commenting) which of both should go into the KG and then please fill out the Google Spreadsheets (link in the first comment of the issue) accordingly.

I suggest that both NeuroSTR and neurostrr go into the KG, as they are two different componentes. If we need to choose one, then choose NeuroSTR (#254). I have filled in the spreadsheets.

**Comment by bweyers** [comment]
@bmihaljevic There is no need to just choose one. I just wanted to be sure that they are actual two different pieces of software. Please also fill out neurostr then. Thanks!

**Comment by bmihaljevic** [comment]
@bweyers I did fill it out, as well. Please let me know if something is still missing.

**Comment by bweyers** [comment]
@bmihaljevic Please be aware that all red fields are mandatory and need to be filled. Especially important is a significant description as this will be the major part of what will show up in the software meta data card. Thus, the description you provided is currently in sufficient and I moved it into the summary field as it fits better there. Please also fill the other red fields.

**Comment by bmihaljevic** [comment]
Done.

**Comment by bweyers** [comment]
Thanks! We will come back on you in case we have further questions.

**Comment by jagru20** [comment]
has been released
