### ISSUE TITLE
ReMoToo 0.0.2

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#317]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=2110394788)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1850962832

**Comment by jagru20** [comment]
To me, this appears to be middleware. Am I wrong?

**Comment by bweyers** [comment]
Sounds reasonable to declare that as a middleware...

**Comment by jagru20** [comment]
released.
