### ISSUE TITLE
Nehuba - Online visualization of large volumetric brain images alpha

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#318]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1870072356

**Comment by jagru20** [comment]
Developer contacted for further information

**Comment by jagru20** [comment]
Developer updated spreadsheet. Please continue integration.

**Comment by jagru20** [comment]
released.
