### ISSUE TITLE
Jupyter Lab 1.2.4

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#32]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=1221442266

**Comment by FeldNico** [comment]
2 TODOs. Then integrate

**Comment by s4safeld** [comment]
I finished integrating the software as far as currently possible

**Comment by s4safeld** [comment]
looking over the data again, I found a list of authors. These authors are listed in the spreadsheet now.

**Comment by FeldNico** [comment]
Released
