### ISSUE TITLE
bsp entity management 1.0.16

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#320]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=56610635

**Comment by herr-zett** [comment]
The only provided [source](https://bbpteam.epfl.ch/documentation/projects/entity-management/1.0.16/index.html) in the Collaboratory-spreadsheet is not accessible. I couldn't find any other information about this software.

**Comment by bweyers** [comment]
There is no information openly accessible to contact developers or continue curation. Thus, issue will be closed.
