### ISSUE TITLE
multipipsa 4.0.2

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#322]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=675317846)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=2127883790

**Comment by jagru20** [comment]
revision completed, please integrate.

**Comment by jagru20** [comment]
released.
