### ISSUE TITLE
Neurorobotics World Simulation Engine 7.2.0.hbp.2.2.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#323]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=38311999

**Comment by PatriziaDuhr** [comment]
please contact developer

**Comment by jagru20** [comment]
replaced by #415
