### ISSUE TITLE
TVB image processing pipeline 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#325]
Original:
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=336640025

Edited:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1184031564

**Comment by BrainModes** [comment]
Fields updated

**Comment by bweyers** [comment]
@herr-zett input from author has been entered into the spreadsheet. Please check for completness.

**Comment by herr-zett** [comment]
I've created a new spreadsheet with additional information.
The original one remained unaltered.

**Comment by BrainModes** [comment]
Hello, it seems that the TVB Image Processing Pipeline has no card in KG. Can it please be added to KG? 

There are cards for MRtrix3_connectome

https://search.kg.ebrains.eu/instances/Software/df2f8f54-af22-4ba3-b381-f03f8f2e89af

and also for fmriprep

https://search.kg.ebrains.eu/instances/Software/7de4c41f-d6f8-4a45-9480-c25ab1ee6772

but these two Docker container images are only components of the pipeline. They shouldn't have their own entries. They should be part of a single card that describes the overall pipeline. As described in the Excel sheet in the cell "Components" the pipeline consists of the components 

MRtrix3_connectome

fMRIPrep

TVB_converter

Can the two existing cards please be removed and instead a single card with the name "TVB Image Processing Pipeline" be generated that contains these three components?

**Comment by jagru20** [comment]
Hello, please note two things:
1. The display of component software in the software card is not yet supported by the KG-search frontend, although the link to it is registered with the software entity.
2. Components can only be linked if they exist as a separate software card in the KG, so deleting the `MRtrix3_connectome` and `fmriprep` card will result in unwanted behavior. Thus I strongly recommend not to delete them.

The fact stated in 2. is the reason we asked for your input in #421, which is, as you stated, a component of the pipeline. And this also leads to the reason why the pipeline was still in the unreleased status: One of the components is not released yet. So please have a look at #421 and give the ok, if you consider the information there as sufficient. We will then release it, too.

The pipeline card should then be available at https://search.kg.ebrains.eu/instances/Software/71265c9f-5fe3-40e3-a7e4-b2bb45b5ea6e?group=curated

**Comment by BrainModes** [comment]
Hi and thanks for your reply.

From my perspective it is not necessary that there exist software cards "MRtrix3_connectome" and "fmriprep" or that there are links from the TVB Pipeline software card to such cards. These are third-party packages (not developed by HBP/EBRAINS) that themselves consist of workflows that combine several other software packages like FreeSurfer, FSL, MRtrix, etc.

With "components" I meant "sub-workflows". It was not clear to me that "components" means "entries in the KG software catalogue".

Next, it wasn't clear to me that you were still waiting for input in #421. The latest activity between 5 Oct and 7 Oct 2020 seemed to indicate that all questions were resolved. Sorry about that!

The open question seems to be "Can this software [TVB_converter] be used as a standalone at all?".

Answer: no, TVB_converter is more like an orchestrator and pre- and postprocessor of inputs and outputs of the two other containers, so I wouldn't consider it as a "standalone software".

The information about TVB_converter in the spreadsheet

https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=230479943

is correct. However, I don't think it should be an independent entry of the software catalogue. It is only used/useable as a part of the TVB Image Processing Pipeline.

**Comment by jagru20** [comment]
In fact, we don't seem to have communicated clearly enough what exactly distinguishes a component. Also in fact, this is precisely the question you identified as still open: "Can it be executed independently?" We mistakenly assumed that you filled out the spreadsheet without comment because that would be the case. Sorry if this has caused any inconvenience. To avoid any further misunderstandings, I'll summarize again: None of the softwares previously marked as components (fmriprep, MRtriX connctome, TVB_Converter) should remain so, i.e. #325 will not have any components linked. Additionally TVB_Converter will be removed from the KG. Correct?

**Comment by BrainModes** [comment]
Yes, this is all correct. Many thanks for the clarification! Thank you.

**Comment by herr-zett** [comment]
@jagru20 Within the KG the links to software entities #421, #418, #419, declaring them as components of #325, have been removed

**Comment by jagru20** [comment]
@herr-zett thanks! released.
