### ISSUE TITLE
The Virtual Brain Neuroinformatics Platform 1.5.8

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#326]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=527034107

**Comment by BrainModes** [comment]
All red fields have been filled out.

**Comment by PatriziaDuhr** [comment]
already done in this issue https://github.com/bweyers/HBPVisCatalogue/issues/44
