### ISSUE TITLE
InTool Explorer 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#327]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1429431006

**Comment by AnnHa2019** [comment]
The web version does not work.

**Comment by jagru20** [comment]
This issue is closed, because the developers did not react to our request for revision.
