### ISSUE TITLE
Multiscale brain simulation with TVB+NEST 1.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#328]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=980433036

**Comment by herr-zett** [comment]
This instance gives the impression of an use case rather than actual software

**Comment by herr-zett** [comment]
Duplicate of #398
