### ISSUE TITLE
Ilastik 1.3.1b

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#33]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=440363073

https://collab.humanbrainproject.eu/#/collab/19/nav/2108?state=software,ilastik
https://www.ilastik.org/

We got the proposition to include the tool Ilastik next. This is in the Catalogue you are processing. Therefore could you process this software next?

**Comment by AnnHa2019** [comment]
Does it have to be this version? There are newer versions

**Comment by FeldNico** [comment]
- Description [here](https://collab.humanbrainproject.eu/#/collab/19/nav/2108?state=software,ilastik) and [here](http://ilastik.github.io/ilastik/overview.html) contradict.
- In collab only version 1.3.2. But newest version is 1.3.3, but there's no sourcecode. A reason?

**Comment by k-dominik** [comment]
Hi, thanks for starting this document. I have tried to leave some comments in the google sheet.

>     * In collab only version 1.3.2. But newest version is 1.3.3, but there's no sourcecode. A reason?

I've updated the entry in the collab. What do you mean by "no sourcecode" ilastik is available on github, source code is always available.

**Comment by FeldNico** [comment]
> Hi, thanks for starting this document. I have tried to leave some comments in the google sheet.
> 
> > ```
> > * In collab only version 1.3.2. But newest version is 1.3.3, but there's no sourcecode. A reason?
> > ```
> 
> I've updated the entry in the collab. What do you mean by "no sourcecode" ilastik is available on github, source code is always available.

Thank you for your help!
with "no sourcecode" we mean that theres no explizit 1.3.3 release on github, only 1.3.2.
In one comment you stated that one of our source documents is outdated. Could you point us to an up to date version we can get our informations from?

**Comment by FeldNico** [comment]
@k-dominik Which is the current up-to-date documentation of this software?

**Comment by FeldNico** [comment]
Developer notified: 10.03.20

**Comment by bweyers** [comment]
@k-dominik Please have a look at the spreadsheet.

**Comment by k-dominik** [comment]
> @k-dominik Please have a look at the spreadsheet.

Hi @bweyers,

I left some comments in January in the google sheet, which don't seem to be taken into account yet. I added some more right now. Or would you prefer a different type of feedback?

**Comment by AnnHa2019** [comment]
Hi @k-dominik 
thank you for your help.
Yes, we prefer a list of authors. Under developer comments you can edit the table as you see fit.

**Comment by AnnHa2019** [comment]
@k-dominik 
thank you!
I added the following remarks.

**Comment by bweyers** [comment]
released
