### ISSUE TITLE
Brain Atlas Viewer 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#331]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1024174429

**Comment by herr-zett** [comment]
Issue #399 seems to already cover this software

**Comment by bweyers** [comment]
@herr-zett could you please shortly comment why you closed this issue. Thanks!

**Comment by herr-zett** [comment]
This issue is indeed a copy of the software already covered by issue #399. Therefore it has been closed
