### ISSUE TITLE
Label-Training 0.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#333]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1294793616

**Comment by AnnHa2019** [comment]
Last github entry nine month ago. It is a scheme for training and applying a label propagation framework.

"It is still work in progress, so don't expect too much from it until it has been properly debugged and refactored, as well as more extensively tested with different settings."

Further research useful?

**Comment by bweyers** [comment]
We should close this issue as software seems to be not further developed and not in a mature state.
