### ISSUE TITLE
hbp-spatial-backend 0.1.0.dev0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#335]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1581753345

**Comment by jagru20** [comment]
reminder sent

**Comment by jagru20** [comment]
developer left feedback. @bweyers is it appropriate to classify a http backend (like this one) as middleware?

**Comment by bweyers** [comment]
@jagru20 I would argue that it is *not* a middleware. I would stick with application in terms of our terminology.

**Comment by jagru20** [comment]
Ok. 

@PatriziaDuhr please go on with integrating as an application then.

**Comment by jagru20** [comment]
Released.
