### ISSUE TITLE
PoSCE 0.1a

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#337]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=511587737)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1188720311

**Comment by jagru20** [comment]
released
