### ISSUE TITLE
HBP Validation Framework - Python Client 0.5.28

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#338]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=933669861

**Comment by jagru20** [comment]
The developer left feedback, please update the spreadsheet and integrate. I would suggest renaming the issue to version 0.5.28 as this seems to be the current release...

**Comment by jagru20** [comment]
has been released
