### ISSUE TITLE
VoluBA - Volumetric Brain Anchoring 0.0.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#339]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=2054527281

**Comment by AnnHa2019** [comment]
VoluBA was edited by Sascha and sent to the developer. This issue can be closed.

**Comment by bweyers** [comment]
Is in curation, thus will be closed.
