### ISSUE TITLE
VIOLA

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#34]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=115084109

**Comment by herr-zett** [comment]
There is no version number provided. Is it v0.1 then or something else?

**Comment by FeldNico** [comment]
Added TODO. After that please integrate.

**Comment by herr-zett** [comment]
Processed TODO

**Comment by FeldNico** [comment]
Initial Email to Developer: 07.01.20

**Comment by FeldNico** [comment]
@bweyers This is your software :( Please revision

**Comment by FeldNico** [comment]
Released
