### ISSUE TITLE
NESTML v3.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#340]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1640138907)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1425033652

**Comment by jagru20** [comment]
released
