### ISSUE TITLE
Brain Simulation Platform Service Account 1.0.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#342]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=2120291840

**Comment by AnnHa2019** [comment]
"Rest API service allowing HBP Collaboratory developers to submit jobs, on behalf of HBP Collaboratory users, on HPC systems"

Is this relevant for us?

**Comment by bweyers** [comment]
We should ask the developers.

**Comment by jagru20** [comment]
Contacted dev

**Comment by jagru20** [comment]
The developer extended the information and wishes to integrate it into the KG. According to the description, I would recommend treating this as middleware (The developer called it "Service", which does not suit our terminology) what do you think?

**Comment by jagru20** [comment]
Developer checked information (communication via email, 28.09.2020) thus "sent for revision" is skipped. Continue with integration.

**Comment by jagru20** [comment]
released.
