### ISSUE TITLE
Human Brain Project HPC Status Monitor 1.0.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#343]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1525342780)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=2082376929

**Comment by jagru20** [comment]
Released
