### ISSUE TITLE
Build your own single cell model using HBP data 1.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#344]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1220744220

**Comment by bweyers** [comment]
Developer has edited the spreadsheet. As the name has changed, please look for the original entity in the KG and change its name too.

**Comment by bweyers** [comment]
Has been released.
