### ISSUE TITLE
Interactive Atlas Viewer v2.2.3

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#345]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=881426693

**Comment by AnnHa2019** [comment]
GitHub link of this application no longer exists. Is this issue still relevant?

**Comment by bweyers** [comment]
@AnnHa2019 please check again as repository still exists.

**Comment by jagru20** [comment]
@dickscheid would you please have a look at the spreadsheet and the contained comments to give us feedback on the collected metadata, before we integrate it into the knowledge graph? Thank you!

**Comment by xgui3783** [comment]
@jagru20 should we change the title of the issue to v2.2.3, in accordance to the spreadsheet link?

I believe my colleague pavel had already made some changes to the spreadsheet. (how) should we inform you when we have made all the necessary corrections and ask for your review? Should we just comment here?

**Comment by jagru20** [comment]
@xgui3783  thanks for your comments. I have integrated your suggested changes and from our side, this is ready to be integrated into the KG now. If you agree, a comment here is totally fine.

**Comment by jagru20** [comment]
released
