### ISSUE TITLE
Single Cell Model Rebuilder Notebook 1.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#347]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=819867987

**Comment by bweyers** [comment]
Developer has edited the spreadsheet. As the name has changed, please look for the original entity in the KG and change its name too.

**Comment by herr-zett** [comment]
@FeldNico I've already started integrating this software into the KG. Shall I continue although you've unassigned me?

**Comment by herr-zett** [comment]
During integration two questions arose:

1. Does the software get the tag "Reviewed"? Though the spreadsheet was edited by the developer, I did not check the entries myself.

2. Amongst other things the developer entered "LGPLv3 with CCA" as a license. I could not find out what CCA stands for. Furthermore I think that the license created in the KG by this software can be deleted.
