### ISSUE TITLE
Insite

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#348]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1508712307

**Comment by bweyers** [comment]
@jagru20 will contact developer to add up to data on insite (as the new incarnation of the in situ pipeline).

**Comment by jagru20** [comment]
Developer contacted

**Comment by jagru20** [comment]
Developer reminded

**Comment by jagru20** [comment]
The developer added information, please revise and expand it, if possible.

**Comment by jagru20** [comment]
I think we should add separate Issues for the insite-nest-module and insite-access-node which are components of Insite.

**Comment by jagru20** [comment]
released: https://kg.ebrains.eu/search/?facet_type[0]=Software&q=insite#Software/eb0b86a5-eb49-4a87-9128-6ca592293218

**Comment by oehrl** [comment]
@jagru20 In the next update (which should be released in the near future) these components will be merged into a single repository so I do not think that it is necessary to have separate issues for them.

**Comment by jagru20** [comment]
Thanks for your answer. Will it be a single repo together with Insite or just the nest module and access node? If the latter is the case, we might list that single repository as a separate KG entry when it is ready.
