### ISSUE TITLE
morphon 0.0.5

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#349]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=259388657)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=235947952

**Comment by jagru20** [comment]
closed due to lack of information for integration.
