### ISSUE TITLE
Landmark-Reg 0.3.0

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#35]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=995756326

**Comment by s4safeld** [comment]
I found this: https://voluba.apps.hbp.eu/#/ 
If you press that little question-mark, you will get this message: "Volumetric Brain Anchoring (VoluBA), was formerly known as Landmark-Reg."
That makes sense since the last commit on the landmark-reg github page is more than a year old. 
Should I discard landmark-reg and change to Voluba, or should I finish landmark-reg and maybe do Voluba after?
In my opinion it makes more sense to discard landmark-reg, and change to Voluba, since it seems to be a direct successor of landmark-reg.

**Comment by s4safeld** [comment]
I propose a new feature type. See comments in spreadsheet

**Comment by FeldNico** [comment]
New Feature was added in last meeting. Please update

**Comment by s4safeld** [comment]
done

**Comment by FeldNico** [comment]
Added one TODO

**Comment by FeldNico** [comment]
Initial Email to Developer: 21.01.2020

**Comment by FeldNico** [comment]
Developer stated that this is outdated and should be removed.
