### ISSUE TITLE
Model Catalog 2.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#350]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1236808186

**Comment by jagru20** [comment]
@apdavison mentioned, that there will be a major release to version 2.0 soon. We will wait with integration until this release and then integrate version 2.0. @apdavison could you please comment here when version 2.0 is released?

**Comment by jagru20** [comment]
@apdavison is this still relevant or is the catalog already curated in a different form?

**Comment by apdavison** [comment]
The catalog is a web service, so would be best represented as such in the KG. I don't know if there is value in also representing the software that underlies the web service?

**Comment by jagru20** [comment]
@apdavison is this actually the model part of the KG search? If yes, we could still curate it, similar to the KG itself (https://search.kg.ebrains.eu/?facet_type[0]=Software&q=KG#0d9249b7-3302-4a84-9c8e-1820658db298) but if you do not want this I think it's fine, I'd close this issue then. Just let me know what you prefer. I agree with you that it is not absolutely necessary.
