### ISSUE TITLE
Model Validation Framework 2.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#351]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=980729630

**Comment by jagru20** [comment]
@apdavison mentioned, that there will be a major release to version 2.0 soon. We will wait with integration until this release and then integrate version 2.0. @apdavison could you please comment here when version 2.0 is released?

**Comment by jagru20** [comment]
Is this a duplicate of #350? The source code entry links to the same repository.

**Comment by jagru20** [comment]
Oh I get it. This one is the umbrella mentioned in [here](https://github.com/bweyers/HBPVisCatalogue/issues/294#issuecomment-684806468)

**Comment by jagru20** [comment]
@apdavison is this still relevant or is the framework already curated in a different form?

**Comment by apdavison** [comment]
I don't think it's relevant for the KG, since it covers multiple components which should have separate entries. You can close this issue.

**Comment by jagru20** [comment]
thanks! closed as suggested.
