### ISSUE TITLE
MoDEL_CNS Database and associated web server beta

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#352]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=365252691)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1507597027

**Comment by herr-zett** [comment]
I've tried to fill in the necessary information.
Being formerly available, the homepage of the software is at this point in time not accessible anymore, unfortunately. Maybe this is just a temporary phenomenon. In any case it would be helpful if the developers could provide some additional information.

**Comment by jagru20** [comment]
@herr-zett , the homepage is accessible again, please have another look if there is more information to be found and update the spreadsheet, if possible.

**Comment by herr-zett** [comment]
With the homepage being accessible again I still couldn't find more relevant information. Perhaps the developers can fill in some more fields of the spreadsheet.

**Comment by jagru20** [comment]
insufficient information, no response by contact person
