### ISSUE TITLE
MIP Algorithm Library -

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#355]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1414809781)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=999239960

**Comment by herr-zett** [comment]
Do this issue and #361 reference the same software?
The Collaboratory of this software links to a collection of [GitHub repositories](https://github.com/search?q=topic%3Aalgorithm-library+org%3ALREN-CHUV+fork%3Atrue) that includes the "[Algorithm repository](https://github.com/LREN-CHUV/algorithm-repository)" which is mentioned in #361.

**Comment by bweyers** [comment]
Closed due to situation that this issue references a collection of software, which cannot be integrated into KG.
