### ISSUE TITLE
sonata network reduction 0.0.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#356]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1599728608

**Comment by PatriziaDuhr** [comment]
very little information found

**Comment by jagru20** [comment]
I suggest closing this issue as there is no contact information available to get more detailed metadata info.

**Comment by bweyers** [comment]
@jagru20 @PatriziaDuhr yes please close the issue in this case and delete the entity from the KG.

**Comment by jagru20** [comment]
KG entity is deleted. Issue closed due to lack of information.
