### ISSUE TITLE
Common Data Elements Database 1.4.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#358]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=938493863)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=75365208

**Comment by herr-zett** [comment]
In the Collaboratory's spreadsheet this repository is referenced:
* [mip-cde-meta-db-setup](https://github.com/LREN-CHUV/mip-cde-meta-db-setup/tree/master)

Within the GitHub-account responsible for this software I've found two other [repositories](https://github.com/LREN-CHUV?q=cde&type=&language=) that seem to be closely related to the one already mentioned:
* mip-meta-db-setup-seed
* mip-cde-data-db-setup

Should I reference all three repositories while working on this software? Or should I only use the one mentioned in the Collaboratoy?

**Comment by jagru20** [comment]
Dear @ludovicc, can you help us out in this question?
We have found these three repositories

> * mip-cde-meta-db-setup
> * mip-meta-db-setup-seed
> * mip-cde-data-db-setup

What we are wondering is, how these three projects are related to each other. Can they be used independently from each other or are they interdependent?

Thanks in advance.

**Comment by jagru20** [comment]
Dear @ludovicc, is there any update on this?

**Comment by bweyers** [comment]
@jagru20 @herr-zett as I understand, this is a data set and thus should have any time of input or output data?

**Comment by jagru20** [comment]
As far as I understood, this is software to manage data from the HBP Medical Pnformatics Platform (MIP) meta database. 
According to the [readme](https://github.com/LREN-CHUV/mip-cde-meta-db-setup/tree/master#introduction), this contains "metadata used for reference"
But you are right, it should be further clarified, which kind of data this is. 

However, considering the facts that the description is thin, it is unclear what data this is about, and that the developer does not react to our contact attempts, we should think again about releasing this, as the metadata available does not really meet the required level of quality.

I will try contacting the other listed contributors before we make a decision.

**Comment by bweyers** [comment]
To be honest, if we do not get feedback, I am reluctant to release this software as it seems not complete. For a database, I need to now how to move data into it and also how to extract it. If is only API based (which I do not think) it might be possible that there are no specific formats available. I also think that the description in the spreadsheet is quite short...

**Comment by jagru20** [comment]
closed due to a lack of information, thus not published in the KG. May be reopened on demand.
