### ISSUE TITLE
NeuroScheme 0.3

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#36]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1088141010

**Comment by FeldNico** [comment]
Initial Email to Developer: 06.01.20

**Comment by herr-zett** [comment]
Under components I listed the software "ViSimpl".
Regarding this entry the developer provided following comment:

_"NeuroScheme and ViSimpl are independent but can work together as well. ViSimpl's source has not been made public yet.
Binaries for both apps are available for Linux, OSX and Windows at http://gmrv.es/gmrvvis/apps/"_

Does ViSimpl still qualify as a component?

**Comment by FeldNico** [comment]
Please do not list it as a component then

**Comment by FeldNico** [comment]
Please integrate

**Comment by bweyers** [comment]
Released
