### ISSUE TITLE
Woken Validation 2.8.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#360]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=189515077

**Comment by jagru20** [comment]
Contacted @Marigold and @ludovicc for revision.

**Comment by jagru20** [comment]
contacted the remaining two authors as @Marigold is not working for HBP anymore and @ludovicc does not react. After two weeks without any reaction I suggest closing this issue.

**Comment by jagru20** [comment]
closed due to insufficient information and unresponsive contact persons. May be reopened on demand.
