### ISSUE TITLE
MIP Algorithm Repository 

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#361]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=455184614)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=999239960

**Comment by jagru20** [comment]
not a software
