### ISSUE TITLE
Tool for management of requests, incidents and problems -

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#363]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1061590871

**Comment by AnnHa2019** [comment]
Little information is available here.

**Comment by bweyers** [comment]
@jagru20 please contact the developer.

**Comment by jagru20** [comment]
Developer contacted

**Comment by jagru20** [comment]
insufficient information
