### ISSUE TITLE
Connectivity-based Psychometric Prediction 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#364]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1421227105)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=778562281

**Comment by herr-zett** [comment]
The cells "License" and "Keywords" are still empty. Maybe one of the developers can provide the missing information necessary for a release of this software?

**Comment by jagru20** [comment]
The developer for now only wants the results from the software integrated into the knowledge graph. Thus this issue is closed and may be reopened on demand.

**Comment by herr-zett** [comment]
Apparently, this software is already covered by issue #388
