### ISSUE TITLE
Functional alignment and template estimation library for functional Magnetic Resonance Imaging data 0.0.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#365]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=2062349665

**Comment by FeldNico** [comment]
Developer said that everything is correct. please integrate

**Comment by AnnHa2019** [comment]
The name changed to fmralign 0.0.1. The old entry was renamed.
