### ISSUE TITLE
Android app for multimodal data acquisition from wearables 1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#366]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=2051577936)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1795257804

**Comment by jagru20** [comment]
The contact E-Mail address is not working, please find out if there is a different contact.

**Comment by herr-zett** [comment]
Updated the developer's E-Mail address with the one he provided on his [GitHub-profile](https://github.com/tomas-teijeiro)

**Comment by herr-zett** [comment]
Due to changes made by the revising developer a new software feature was proposed in issue #424. If it is accepted, the KG-entry of this software has to be updated

**Comment by herr-zett** [comment]
> Due to changes made by the revising developer a new software feature was proposed in issue #424. If it is accepted, the KG-entry of this software has to be updated

Done

**Comment by jagru20** [comment]
Released.
