### ISSUE TITLE
ChemBioServer 2

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#368]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1240817313

**Comment by AnnHa2019** [comment]
just edited. Issue can be deleted

**Comment by FeldNico** [comment]
This is already curated https://github.com/bweyers/HBPVisCatalogue/issues/78
