### ISSUE TITLE
Synaptic plasticity 0.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#371]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=701371947

**Comment by AnnHa2019** [comment]
Listed in Brain Simulation Platform as use case.

**Comment by bweyers** [comment]
@AnnHa2019 it seems to be a Jupyter Notebook for which we have a specific application type. 
@jagru20 please contact developer to let fill in the schema.

**Comment by jagru20** [comment]
Contacted developer

**Comment by jagru20** [comment]
released
