### ISSUE TITLE
TVB-HPC v1.0-beta

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#373]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=980890540

**Comment by PatriziaDuhr** [comment]
found new version on github, updated name

**Comment by jagru20** [comment]
developer left feedback, please integrate

**Comment by jagru20** [comment]
released
