### ISSUE TITLE
Ontology Lookup Service for Translational Neurodegeneration Research OLS-Neuro-2020

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#375]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1930102843)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=469550323

**Comment by herr-zett** [comment]
@jagru20 @bweyers 
The only source mentioned in the Collaboratory refers to this [website](http://rohan.scai.fraunhofer.de/).
By following the link this message is presented:
<pre>
<b>It works !</b>
If you're seeing this page via a web browser, it means you've setup Tomcat successfully. Congratulations!

This is the default Tomcat home page. It can be found on the local filesystem at: /var/lib/tomcat8/webapps/ROOT/index.html

Tomcat8 veterans might be pleased to learn that this system instance of Tomcat is installed with CATALINA_HOME in /usr/share/tomcat8 and CATALINA_BASE in /var/lib/tomcat8, following the rules from /usr/share/doc/tomcat8-common/RUNNING.txt.gz.

You might consider installing the following packages, if you haven't already done so:

tomcat8-docs: This package installs a web application that allows to browse the Tomcat 8 documentation locally. Once installed, you can access it by clicking <a href="https://rohan.scai.fraunhofer.de/docs/">here</a>.

tomcat8-examples: This package installs a web application that allows to access the Tomcat 8 Servlet and JSP examples. Once installed, you can access it by clicking <a href="https://rohan.scai.fraunhofer.de/examples/">here</a>.

tomcat8-admin: This package installs two web applications that can help managing this Tomcat instance. Once installed, you can access the <a href="https://rohan.scai.fraunhofer.de/manager/html">manager webapp</a> and the <a href="https://rohan.scai.fraunhofer.de/host-manager/html">host-manager webapp</a>.

NOTE: For security reasons, using the manager webapp is restricted to users with role "manager-gui". The host-manager webapp is restricted to users with role "admin-gui". Users are defined in /etc/tomcat8/tomcat-users.xml.
</pre>

Searching for the software directly on the website of the [Fraunhofer Institut](https://www.fraunhofer.de/) provides only one [result](https://www.scai.fraunhofer.de/en/business-research-areas/bioinformatics/projects/Rohan.html) mentioning the software.

How should we proceed further?

**Comment by bweyers** [comment]
@herr-zett @jagru20  I would suggest to contact the developer and ask, first, whether the software is under further developement and should be integrated, and if first applies, secondly ask the developer for inputing the information into the spreadsheet.

**Comment by jagru20** [comment]
The developer has been contacted, waiting for reply.

**Comment by jagru20** [comment]
Website reachable now. @herr-zett continues.

**Comment by jagru20** [comment]
Dear @johannes-darms, we are trying to integrate metadata about your ontology lookup service into the EBRAINS knowledge graph. Could you please have a look at the [spreadsheet](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1930102843) and fill it with accurate information? Thank you!

**Comment by johannes-darms** [comment]
Hi @jagru20, sorry about the late response. I'm no longer working for Fraunhofer SCAI and hence cannot help you there.
You can contact Mr. Marc Jacobs [marc.jacobs@scai.fraunhofer.de] (https://github.com/MarcZimmermann). I'll be happy to help you.

If just checked the URL an the service is accessible and is working.

**Comment by jagru20** [comment]
Contacted Marc Jacobs

**Comment by jagru20** [comment]
insufficient information
