### ISSUE TITLE
SCAIView-NEURO

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#376]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=995906393

**Comment by jagru20** [comment]
this seems to be corrupted in some way. First off the given mail adresses are not valid anymore, second the linked homepage is dead. Please check if this software is still available.

**Comment by jagru20** [comment]
@bweyers, is it valid to integrate software that is not licensed under a specific, commonly known license?

**Comment by bweyers** [comment]
@jagru20 in principal yes. We have the option to define the lincense with "no license".

**Comment by jagru20** [comment]
released: https://kg.ebrains.eu/search/instances/software/e80b83f8-f6e7-46f1-aaaf-b795c4388b0e
