### ISSUE TITLE
multiMap

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#381]
This Software was encountered during integration of [Neurosuites](https://github.com/bweyers/HBPVisCatalogue/issues/27).
@gherardovarando
[Spreadsheet](https://docs.google.com/spreadsheets/d/14GvpXEBavBnCAsGstx783wq0O_I1NwuzpJUfTPOBmXY/edit?usp=sharing)

**Comment by gherardovarando** [comment]
I am not maintaining MultiMap and related code. It should still work but I am not planning on fixing bugs/improving etc. 
The map visualization part is available through an Atom package https://atom.io/packages/map-viewer and 
I am still maintaining the leaflet plugins (https://github.com/gherardovarando/leaflet-map-builder, https://github.com/gherardovarando/leaflet-csvtiles, https://github.com/gherardovarando/leaflet-multilevel)

**Comment by gherardovarando** [comment]
MultiMap was based on electrongui (https://github.com/gherardovarando/electrongui) which is now completely outdated

**Comment by gherardovarando** [comment]
The ImageJ object detection part is available directly as a ImageJ plugin https://github.com/ComputationalIntelligenceGroup/obj_detection_toolset

**Comment by jagru20** [comment]
closing as MultiMap is not actively developed anymore
