### ISSUE TITLE
OpenElectrophy

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#387]
This Software was encountered during integration of [Neo](https://github.com/bweyers/HBPVisCatalogue/issues/13).
[Spreadsheet](https://docs.google.com/spreadsheets/d/1DHbm_2KQxUahNPlQFxTiSJPt38qxBB1YLKTsItBIUMI/edit?usp=sharing)
@samuelgarcia

**Comment by samuelgarcia** [comment]
Hi.
The OpenElectrophy software is dead and unmaintain since some year now.
I don't think it is valuable to integrate it in a globale catalogue of software anymore.

**Comment by jagru20** [comment]
@samuelgarcia, thank you for giving the answer for our question before we even asked! That's efficiency at its best.

**Comment by jagru20** [comment]
The software will not be curated and thus this issue is closed.
