### ISSUE TITLE
3D Slicer 4.10.2

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#389]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=984033640

**Comment by herr-zett** [comment]
There is an instance of this software in the KG with a lower version number (4.10.1). Should it be deleted or can it remain in the KG as it covers another version?

**Comment by bweyers** [comment]
Thus, you created a new entity for version 4.10.2 and added the meta data. Still, there is an entity for another version (4.10.1) in the KG? I guess the latter happend due to the automatic integration from the Collab Catalog. Just keep the 4.10.1 in the KG as it might be integrated later.

**Comment by herr-zett** [comment]
Version 4.10.1 has been integrated by @FeldNico in october last year.

**Comment by bweyers** [comment]
Should be kept and associated to the software project 3D Slicer. Thus, two version exists then.
