### ISSUE TITLE
Vishnu 1.0

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#39]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=2023685526

**Comment by FeldNico** [comment]
Added TODOs

**Comment by AnnHa2019** [comment]
Edited TODOs

**Comment by FeldNico** [comment]
Developer will be notified soon

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer provided information. Please check and integrate.

**Comment by AnnHa2019** [comment]
To be released, but additions/changes are still necessary

**Comment by FeldNico** [comment]
released
