### ISSUE TITLE
ImageJ 2.0.0-rc-72

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#390]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1022486463

**Comment by bweyers** [comment]
Reminder sent

**Comment by bweyers** [comment]
Reminder sent

**Comment by FeldNico** [comment]
no feedback from developer. please integrate.

**Comment by bweyers** [comment]
has been released
