### ISSUE TITLE
MRIcron v1.0.20190902

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#391]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=393355038

**Comment by herr-zett** [comment]
In the latest [release notes](https://www.nitrc.org/frs/shownotes.php?release_id=4142) of this software it is recommended to upgrade to the software [MRIcroGL](https://github.com/rordenlab/MRIcroGL12).
Should this issue therefore be changed to cover the newer software MRIcroGL?

**Comment by herr-zett** [comment]
In the latest [release notes](https://www.nitrc.org/frs/shownotes.php?release_id=4142) of this software it is recommended to upgrade to the software [MRIcroGL](https://github.com/rordenlab/MRIcroGL12).
Should this issue therefore be changed to cover the newer software MRIcroGL?

**Comment by FeldNico** [comment]
Please do both

**Comment by bweyers** [comment]
04-05-20 sent for revision

**Comment by FeldNico** [comment]
Devloper left feedback. Please check&integrate.

**Comment by bweyers** [comment]
Has been released!
