### ISSUE TITLE
Update on KG entry for Elephant tool

### ISSUE THREAD

**Issue by mdenker** [bweyers/HBPVisCatalogue#392]
Updates marked **in red** in this copy of the original document under the Elephant tab:
https://docs.google.com/spreadsheets/d/12uibUnJLz9LEt_J2LngpDVCII7qA2f_EOqiMZBUm8n4/edit?usp=sharing

KG entry:
https://kg.ebrains.eu/search/?facet_type[0]=Software&q=Elephant

**Comment by bweyers** [comment]
Has been released.
