### ISSUE TITLE
MRIcroGL v1.2.20200331

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#393]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1857589158

**Comment by bweyers** [comment]
04-05-20 sent for revision.

**Comment by FeldNico** [comment]
Developer left feedback. Please check&integrate.

**Comment by bweyers** [comment]
Has been released
