### ISSUE TITLE
Nilearn 0.6.2

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#395]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1893041759

**Comment by bweyers** [comment]
Author notified.

**Comment by bweyers** [comment]
Reminder sent.

**Comment by FeldNico** [comment]
No feedback from developer. Please integrate.

**Comment by bweyers** [comment]
has been released
