### ISSUE TITLE
SNT 3.1.105

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#396]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1898536402

**Comment by bweyers** [comment]
04-05-20 Send for revision to author

**Comment by FeldNico** [comment]
Reminder sent

**Comment by jagru20** [comment]
Developer left feedback, please integrate

**Comment by herr-zett** [comment]
The developer noted, that a new paper about this software will soon be released and that he will update the spreadsheet accordingly. Once this is done the KG-entry should be updated.

**Comment by jagru20** [comment]
released
