### ISSUE TITLE
The Virtual Brain Web-App

### ISSUE THREAD

**Issue by BrainModes** [bweyers/HBPVisCatalogue#397]
[01_TVB_WebApp.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4501496/01_TVB_WebApp.xlsx)

**Comment by bweyers** [comment]
@AnnHa2019 please work on this next.

**Comment by AnnHa2019** [comment]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=1250133878

**Comment by AnnHa2019** [comment]
Some comments noted for the developers.

**Comment by bweyers** [comment]
@BrainModes We have revised the sheet. Please have a look and comment/add/edit the content due to our comments. Thanks!

**Comment by BrainModes** [comment]
Thanks. Commented, added and edited information.

**Comment by FeldNico** [comment]
Developer left comment. Please check and if no further questions please integrate.

**Comment by bweyers** [comment]
has been released
