### ISSUE TITLE
Multi-scale brain simulation with TVB-NEST 1.5.8

### ISSUE THREAD

**Issue by BrainModes** [bweyers/HBPVisCatalogue#398]
[02_TVB_NEST.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4501544/02_TVB_NEST.xlsx)

**Comment by bweyers** [comment]
@herr-zett please work on this next.

**Comment by bweyers** [comment]
@herr-zett please post Google Spreadsheet. Otherwise we cannot have a look at it and also not share it with the authors.

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1606701961

**Comment by bweyers** [comment]
@BrainModes We have worked on the sheet and let various comments and questions. Please revise and let us know when you are done.

**Comment by FeldNico** [comment]
@BrainModes While curating this software we stumpled on the following issues:
- Which version is correct? 1.5.8, or 1.1 (Collaboratory Entry) or 1.0.1 (Release on github)
- Is this the Docker-version from https://github.com/bweyers/HBPVisCatalogue/issues/401?
  If yes: What do you think about merging these two?

**Comment by BrainModes** [comment]
All questions have been addressed in the google sheet. Version 1.0.1 is correct.
Yes we have a docker version and a Web App version of this software. In principle this can be merged.

**Comment by bweyers** [comment]
@BrainModes Thanks!
@AnnHa2019 @herr-zett please integrate!

**Comment by BrainModes** [comment]
Dear Benni, dear all, we would be very grateful if the TVB tools could be released in KG before the EC review next week.  We claim they are findable via KG in our little video: https://youtu.be/_G_DjRb1ams :-)
Thanks a lot, Petra

**Comment by bweyers** [comment]
has been released
@BrainModes Petra, I hope that all entities are released now.
