### ISSUE TITLE
Interactive TVB Brain Atlas Viewer

### ISSUE THREAD

**Issue by BrainModes** [bweyers/HBPVisCatalogue#399]
[03_TVB_Atlas.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4501755/03_TVB_Atlas.xlsx)
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1526505213

**Comment by bweyers** [comment]
@PatriziaDuhr Please start to work on this entry next.

**Comment by PatriziaDuhr** [comment]
Can't find much information

**Comment by bweyers** [comment]
@BrainModes thanks for providing the information. Please add more details into the description and also give a specific data for the create at field. Best would be the take the date on which the release 1.0 was published.

**Comment by BrainModes** [comment]
Dear Benjamin. This has been done. When do you expect the curation of this tool being finalized and the Interactive TVB Brain Atlas Viewer being findable via EBRAINS KG? Thanks a lot! Petra

**Comment by bweyers** [comment]
Dear Petra! We will now continue with integration into the KG. In the moment we released it, you will get a notification that this issue is closed. Thus should not take much more time than a week. 

@PatriziaDuhr Please integrate!

**Comment by BrainModes** [comment]
Thanks a lot, Benni!

**Comment by bweyers** [comment]
has been released
