### ISSUE TITLE
DataVizCatalogue

### ISSUE THREAD

**Issue by flangel3** [bweyers/HBPVisCatalogue#4]
Kurze Recherche

**Comment by flangel3** [comment]
Habe mir den Katalog angeguckt. Wie du schon geschrieben hast, ist es die selbe Thematik.

Allerdings liefert unsere geplante Ontologie deutlich mehr Details für den Bereich (medizinische) Bildverabeitung. Ein Volumengraph ist z.b. nicht mal in irgendeiner Form enthalten und die Datensätze werden nicht angesprochen.

Mit DataVizCatalogue kann man dafür sehr gut ziemlich spezielle und unübliche Graphen finden.

**Comment by bweyers** [comment]
TODO: Erzeugen einer Liste von bereits existierenden Listen im Repository
