### ISSUE TITLE
TVB+NEST Web App

### ISSUE THREAD

**Issue by BrainModes** [bweyers/HBPVisCatalogue#401]
[04_TVB_NEST_webapp.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4537779/04_TVB_NEST_webapp.xlsx)

**Comment by AnnHa2019** [comment]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=1107971825

**Comment by bweyers** [comment]
@herr-zett @AnnHa2019 Please integrate software as soon as possible. Would be good to have the entity released in the beginning of next week.

**Comment by jagru20** [comment]
has been released
