### ISSUE TITLE
ZetaStitcher

### ISSUE THREAD

**Issue by gmazzamuto** [bweyers/HBPVisCatalogue#402]
[Template-ZetaStitcher.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4554493/Template-ZetaStitcher.xlsx)

**Comment by AnnHa2019** [comment]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=1136002775

**Comment by bweyers** [comment]
@gmazzamuto thanks for providing the meta data. We have now entered it into a google spredasheet (see above). Please check and also provide a email adress or URL for a location that provides help.

**Comment by gmazzamuto** [comment]
updated

**Comment by FeldNico** [comment]
Please integrate

**Comment by bweyers** [comment]
has been released

**Comment by gmazzamuto** [comment]
May I ask you where the released software are released? so that I can add the link in relevant HBP reports and documents

thanks a lot

**Comment by jagru20** [comment]
Excuse me for splitting hair, but just to avoid misunderstandings: Strictly speaking not the software but only the collected metadata is published in the EBRAINS knowledge graph. The metadata can be viewed under the link https://kg.ebrains.eu/search/?facet_type[0]=Software&q=zeta#Software/85c7bd09-e0e6-42d8-873d-a60f612ae6ac. 

The Knowledge Graph Search-UI can be reached at https://kg.ebrains.eu/search
