### ISSUE TITLE
Surf Ice v1.0.20190902

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#404]
https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage.

This was suggested by Chris Roden

**Comment by AnnHa2019** [comment]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=1548513336

**Comment by jagru20** [comment]
is there any developer mail address available?

**Comment by AnnHa2019** [comment]
yes, i added an adress.

**Comment by jagru20** [comment]
released
