### ISSUE TITLE
NEST Desktop 2.4.1

### ISSUE THREAD

**Issue by bweyers** [bweyers/HBPVisCatalogue#405]
[nest-desktop-fb4.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4627491/nest-desktop-fb4.xlsx)
https://docs.google.com/spreadsheets/d/1zsNRt2bumhpBtWGFjH5iqaCXKXCuHGnTOzFgt1iYO2A/edit?usp=sharing

**Comment by jagru20** [comment]
released
