### ISSUE TITLE
Neuronizev2 2.0.0

### ISSUE THREAD

**Issue by ghost** [bweyers/HBPVisCatalogue#406]
[Template_Neuronize.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4656093/Template_Neuronize.xlsx)

**Comment by AnnHa2019** [comment]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=1255864864

**Comment by AnnHa2019** [comment]
Is Neuronize V2 an extension of Neuronize?

**Comment by bweyers** [comment]
@AnnHa2019 that we need to ask the developer...

**Comment by ivanvelascog** [comment]
@AnnHa2019 Yes, Neuronize V2 is an extension of Neuronize. We are working on a publication for this new version.

**Comment by bweyers** [comment]
@AnnHa2019 I would then suggest to continue curation and refer to Neuronize as component.

**Comment by jagru20** [comment]
reminder sent

**Comment by jagru20** [comment]
released
