### ISSUE TITLE
NeuroScheme 0.3

### ISSUE THREAD

**Issue by odrobles** [bweyers/HBPVisCatalogue#407]
[Template-vis_catalog-NeuroScheme.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4812603/Template-vis_catalog-NeuroScheme.xlsx)

**Comment by AnnHa2019** [comment]
NeuroScheme 0.3 has already been edited by Daniel, I only added the author's information. 
[link to software: https://kg-editor.humanbrainproject.eu/instance/view/softwarecatalog/software/software/v1.0.0/9ec27084-9075-4efa-9920-ea343d2885f1]

**Comment by jagru20** [comment]
has been released
