### ISSUE TITLE
NeuroTessMesh 0.0.1

### ISSUE THREAD

**Issue by odrobles** [bweyers/HBPVisCatalogue#408]
[Template-vis_catalog-NeuroTessMesh.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4812610/Template-vis_catalog-NeuroTessMesh.xlsx)

**Comment by AnnHa2019** [comment]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=107692475

**Comment by jagru20** [comment]
Developer: @juanjosegarcan

**Comment by jagru20** [comment]
@juanjosegarcan, did you complete the revision process and agree with the information in the metadata sheet?

**Comment by jagru20** [comment]
developer left feedback, @PatriziaDuhr please check and continue integration

**Comment by jagru20** [comment]
Released
