### ISSUE TITLE
Score-P 6.0

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#41]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=931360132

**Comment by FeldNico** [comment]
Added TODOs

**Comment by herr-zett** [comment]
Processed TODOs

**Comment by FeldNico** [comment]
Answered questions.
Developer will be notified soon

**Comment by FeldNico** [comment]
Developer notified: 24.02.20

**Comment by FeldNico** [comment]
Developer reminded: 16.03.20

**Comment by bweyers** [comment]
@herr-zett Please revise the comments from the author accordingly.

**Comment by herr-zett** [comment]
Added 6 questions in consequence of processing the developer's comments

**Comment by bweyers** [comment]
@herr-zett I answered all questions. Please revise and integrate.

**Comment by bweyers** [comment]
Has been released.
