### ISSUE TITLE
CerebModels 0.3.0

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#410]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=772431244

**Comment by herr-zett** [comment]
I couldn't fill in all necessary information. Perhaps the developer can provide information for the missing entries.

**Comment by jagru20** [comment]
Dear @lungsi,

we are currently in the process of gathering meta data on your software "CerebModels 0.3.0" to integrate it into the HBP Knowledge Graph. Unfortunately we struggle to find sufficient information. Could you please have a look at the spreadsheet and fill in at least the fields marked in red?
Thank you for your help!

HBP Software Curation Team

**Comment by jagru20** [comment]
This issue is closed for two reasons:
1. There is too little information publicly available to meet our quality standards in metadata curation. 
1. The person we have the contact information of does not react to our requests for more information.
