### ISSUE TITLE
New version of Nutil released

### ISSUE THREAD

**Issue by Majpuc** [bweyers/HBPVisCatalogue#411]
Hi, 
We released a new version with important changes
https://docs.google.com/spreadsheets/d/1rwiraz0yZsNgt8cd24_pXypSRvSMJr3nvsURQUkJF0M/edit?usp=sharing

Thanks!

**Comment by bweyers** [comment]
@Majpuc thanks for the spreadsheet
@herr-zett please add new version similar to how we did it for elephant

**Comment by herr-zett** [comment]
Changes processed and new KG-entry created.
(Nexus ID: softwarecatalog/software/software/v1.0.0/5badddb6-4906-4274-8976-0b3a3fa74f07)

@jagru20 @bweyers There a two licenses mentioned in the spreadsheet:
* CC BY-NC-SA 4.0 for the documentation
* GNU GPLv3 for the code

For now I've only included the GPLv3-license in the KG-entry. Is the other license for the documentation required to be mentioned as well?

**Comment by Majpuc** [comment]
New EBRAINS sw licensing guidelines are in preparation. I've updated this info according to advice from TC manager.

**Comment by jagru20** [comment]
has been released
