### ISSUE TITLE
CerebData

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#412]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=353432860

**Comment by herr-zett** [comment]
Unfortunately the [documentation](https://cerebdata.readthedocs.io/en/latest/) is not that helpful for filling in all necessary information.

**Comment by jagru20** [comment]
Dear @lungsi,

we are currently in the process of gathering meta data on your software "CerebData" to integrate it into the HBP Knowledge Graph. Unfortunately we struggle to find sufficient information. Could you please have a look at the spreadsheet and fill in at least the fields marked in red?
Thank you for your help!

HBP Software Curation Team

**Comment by jagru20** [comment]
This issue is closed for two reasons:
1. There is too little information publicly available to meet our quality standards in metadata curation. 
1. The person we have the contact information of does not react to our requests for more information.
