### ISSUE TITLE
Neuron Segmentation Tool

### ISSUE THREAD

**Issue by jagru20** [bweyers/HBPVisCatalogue#414]
[](https://github.com/bweyers/HBPVisCatalogue/files/4914384/Template-Neuron.Segmentation.Tool.xlsx)

@filippocastelli @gmazzamuto
[Spreadsheet](https://docs.google.com/spreadsheets/d/1uyL2i0J14spQFlk_v7aVJ6UxCk2p2_kBVn2POCVzHik/edit?usp=sharing)

**Comment by jagru20** [comment]
@filippocastelli and @gmazzamuto, we have collected some additional information on the Neuron Segmentation Tool. Could you please have a look at the spreadsheet? Please leave a comment in the "Developer Comments" column if something bothers you.  After this we will continue integrating the meta data into the Knowledge Graph. Thanks!

**Comment by gmazzamuto** [comment]
Looks good to me, thanks!

**Comment by jagru20** [comment]
released
