### ISSUE TITLE
OTF2 2.2

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#416]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=917650797

**Comment by herr-zett** [comment]
@jagru20 @bweyers
During integration into the KG the following problem arose when saving the instance:
Within the fields "Release Notes" and "Help" a slash "/" was added to the beginning of each line of the text that was entered.

**Comment by jagru20** [comment]
@herr-zett the slash is added, because those fields expect an URL and thus change the entries into a relative path.

**Comment by herr-zett** [comment]
@jagru20 As I can't provide URLs for the affected entries, shall I leave it as is?

**Comment by jagru20** [comment]
found a link. released!
