### ISSUE TITLE
fMRIPrep 20.1.1

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#419]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1797040849

**Comment by jagru20** [comment]
Developer left feedback, please integrate.

**Comment by herr-zett** [comment]
@jagru20 @bweyers 
Developer added following link into the field "Components": [www.nipreps.org](https://www.nipreps.org/)

According to this website NiPreps (NeuroImaging PREProcessing toolS) appears to be a collection of different applications that adhere to the [BIDS-App standard](https://www.nipreps.org/apps/framework/).
Therefore I wouldn't add NiPreps as component of fMRIPrep.

**Comment by jagru20** [comment]
released
