### ISSUE TITLE
VoluBA (4.01.2020)

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#42]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=381867229

**Comment by s4safeld** [comment]
read latest comment on landmark-reg issue:
https://github.com/bweyers/HBPVisCatalogue/issues/35

**Comment by s4safeld** [comment]
I propose a new feature type. See comments in spreadsheet

**Comment by s4safeld** [comment]
Can't fill all required fields.

**Comment by FeldNico** [comment]
Initial Email to Developer: 21.01.2020

**Comment by FeldNico** [comment]
Developer to contact: Xiao Gui

**Comment by FeldNico** [comment]
Contacted Xiao

**Comment by bweyers** [comment]
Please integrate.

**Comment by bweyers** [comment]
Has been released.
