### ISSUE TITLE
Metadata Scheme Adaptions - Middleware

### ISSUE THREAD

**Issue by PatriziaDuhr** [bweyers/HBPVisCatalogue#420]
**Category:** Application Category

**Triggering Case:** [Unicore](https://github.com/bweyers/HBPVisCatalogue/issues/400)

**Problem:** We do not have a suitable application category that fits this software, as it is described as middleware. 

**Proposal:** Add middleware as a new application category.

**Comment by bweyers** [comment]
I think that this is a good decision! @jagru20 Could you please add this catagory to our documentation in the Wiki? It might be easy to add this category to the KG.

**Comment by jagru20** [comment]
Done.
