### ISSUE TITLE
TVB_converter

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#421]
Spreadsheet:

https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=230479943

This software is a component of #325 and was regarded relevant enough to be integrated into the KG (see following comments of issue #325: [question](https://github.com/bweyers/HBPVisCatalogue/issues/325#issuecomment-642043837), [answer](https://github.com/bweyers/HBPVisCatalogue/issues/325#issuecomment-642086249))

Other than an entry on [DockerHub](https://hub.docker.com/r/thevirtualbrain/tvb_converter) I couldn't find any information about this software.

Note:
I've stumbled upon a repository on GitHub called [tvb-pipeline-converter](https://github.com/BrainModes/tvb-pipeline-converter). Upon further investigation it became apparent, that this repository is not identical to TVB_converter. TVB_converter is rather a component of tvb-pipeline-converter according to this [source](https://wiki.ebrains.eu/bin/view/Collabs/tvb-pipeline).

**Comment by jagru20** [comment]
@bweyers in my opinion, this docker Container is very specific for the use in the TVB image processing pipeline (#325) and not inteded to be used with other data. Thus I would suggest one of the following:

1. Not to treat it as separate Software or a Component 
or
2. Consult the developer to fill in the required info.

What do you think?

**Comment by bweyers** [comment]
@jagru20 we should ask the developer I guess...

**Comment by jagru20** [comment]
Dear @BrainModes,

we are currently in the process of integrating the software "TVB_converter" as a component of the "TVB image processing pipeline" into the EBRAINS Knowledge Graph. However, we can not find sufficient information on this component and thus need your help. 
Can this software be used as a standalone at all? If so, could you please fill in the required information in the spreadsheet (red fields) under the following link:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=230479943

Thank you in advance!

**Comment by jagru20** [comment]
@herr-zett, the developer extended the information. Please check.

**Comment by herr-zett** [comment]
The links provided as Documentation (cell B23) are the same as for the software in issue #325. Probably due to the fact that this software is a component of #325.

**Comment by jagru20** [comment]
Closed Without release. see discussion in #325
