### ISSUE TITLE
Nutil software

### ISSUE THREAD

**Issue by sharoncy** [bweyers/HBPVisCatalogue#423]
The Nutil software card needs to be updated:

- The source code link has been changed to: https://github.com/Neural-Systems-at-UIO/nutil/ 
- We have a new citation: Groeneboom NE, Yates SC, Puchades MA and Bjaalie JG (2020) Nutil: A Pre- and Post-processing Toolbox for Histological Rodent Brain Section Images. Front. Neuroinform. 14:37. doi: 10.3389/fninf.2020.00037

Sharon Yates

**Comment by jagru20** [comment]
Dear @sharoncy, the DOI in the citation matches the wrong title, i suppose you are talking about 

Groeneboom NE, Yates SC, Puchades MA and Bjaalie JG (2020) Nutil: A Pre- and Post-processing Toolbox for Histological Rodent Brain Section Images. Front. Neuroinform. 14:37. doi: 10.3389/fninf.2020.00037

correct?

**Comment by jagru20** [comment]
Sorry I was mistaken and therfore deleted my previous comment.

**Comment by jagru20** [comment]
The new infos have been integrated.
