### ISSUE TITLE
SimPart

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#425]
This software is a component of ViSimpl #314 

Other than these two articles ([1](https://www.frontiersin.org/articles/10.3389/fninf.2016.00044/full),[2](https://arxiv.org/pdf/2003.06343.pdf)), that mention and give brief descriptions of SimPart as a component of ViSimpl, I couldn't find a repository or documentation providing in depth information about this software.

Should the developers of ViSimpl be contacted?

**Comment by jagru20** [comment]
@vg-lab, do you want SimPart to be integrated into the EBRAINS Knowledge Graph? If yes, please fill out this spreadsheet: https://docs.google.com/spreadsheets/d/1N9Ckmk8ylSyKqkxoVIcTv6r4PeE3NitCYi9Zp4xpxZA/edit?usp=sharing Thank you!

**Comment by jagru20** [comment]
As we did not receive an answer, we assume there is no interest in integrating this.
