### ISSUE TITLE
PIPSA

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#426]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1558244140

This software is a component of multipipsa #322 

In the latest [release notes](https://projects.h-its.org/mcmsoft/pipsa/4.0.2/availability.html) of this software provided on the [homepage](https://pipsa.h-its.org/pipsa/pipsa-docu.jsp) it is stated that:
> PIPSA code is now included in a python wrapper that allows to run multiple PIPSA runs on different parts of the protein.

> Newly added python wrapper called multipipsa is available under the EUPL license conditions. The original PIPSA code, which is part of the multipipsa package, is available for use according to the license at "Terms and Conditions" also within the package.

This python wrapper refers to multipipsa.

My question is, whether PIPSA is still relevant as a standalone application that has to be integrated into the KG? It seems to me, that it was superseded by the more advanced tool multipipsa.

**Comment by bweyers** [comment]
Move further information from pipsa to multipipsa #322 and close this issue as pipsa is part of mutlipipsa
