### ISSUE TITLE
LePetitPrince

### ISSUE THREAD

**Issue by jagru20** [bweyers/HBPVisCatalogue#427]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1348793868

**Comment by jagru20** [comment]
@herr-zett please integrate this next.

**Comment by herr-zett** [comment]
@bweyers @jagru20 Developer mentioned "nifti images (3D/4D)" as Data Types.
For now I've added "Time Series Data Types", "3D-Scalar Data Types" and "3D-Vector Data Types" into the KG. Is this a sufficient representation?

**Comment by jagru20** [comment]
Yes, it is.

**Comment by jagru20** [comment]
Is released now.

**Comment by jagru20** [comment]
Dear @AlexandrePsq and @chrplr,

in the information you gave us at the time of the curation, you stated that the Source Code of LePetitPrince is under BSD-License. For the migration to a new meta data schema, we need information about which BSD-License exactly you mean, as the term "BSD-License" refers to the set of all BSD Licenses. Could you please provide this information? Maybe it is worth the thought of integrating the license into your github repository.

Thank you

Jan
