### ISSUE TITLE
Clint Explorer 0.1

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#43]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=2013745957

**Comment by FeldNico** [comment]
Developer will be notified soon

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer reminded: 17.03.20

**Comment by bweyers** [comment]
Please integrate.

**Comment by bweyers** [comment]
released
