### ISSUE TITLE
Lempel Ziv Perturbational Complexity Index

### ISSUE THREAD

**Issue by thierrynieus** [bweyers/HBPVisCatalogue#433]
Dear HBP software support team. I would like to have our software for the calculation of the complexity index included in your catalogue. I attach the template file I have been asked to fill in a previous email exchange.

[](https://github.com/bweyers/HBPVisCatalogue/files/5234283/Template-1.xlsx)
https://docs.google.com/spreadsheets/d/1jeTAk-_53BHYyJ6UfGIzqHaqR2x3XcwXxjOk9RHSG_A/edit?usp=sharing

**Comment by jagru20** [comment]
@PatriziaDuhr  the Description was updated. I think we can continue the integration now.

**Comment by jagru20** [comment]
released
