### ISSUE TITLE
SpectralSegmentation 1.0

### ISSUE THREAD

**Issue by chrisvdt** [bweyers/HBPVisCatalogue#434]
[SpecSeg.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/5219090/SpecSeg.xlsx)

[Spreadsheet](https://docs.google.com/spreadsheets/d/1TJqMcLfbf1JViiUG3rhF8SFk38Vx7vFA_eD_pt402x0/edit?usp=sharing)

**Comment by jagru20** [comment]
@chrisvdt please have another look at the changes we made to the metadata in the [spreadsheet](https://docs.google.com/spreadsheets/d/1TJqMcLfbf1JViiUG3rhF8SFk38Vx7vFA_eD_pt402x0/edit?usp=sharing) and give us feedback. If you are fine with it, we will integrate it. Please also add the creation date in the "Created at" field.

**Comment by chrisvdt** [comment]
@jagru20 I've had a look at the updated spreadsheet, and added the creation date. The rest looks fine to me, except the links to the authors. I realize you could not ad a link to Leander, I'll see if we can mend this, so we can add him as well, he has done a lot of work on this toolbox.

**Comment by jagru20** [comment]
released: https://kg.ebrains.eu/search/?facet_type[0]=Software#Software/90368a62-42ea-481d-a95c-818419b95c14

**Comment by PatriziaDuhr** [comment]
added citation to spreadsheet and KG
