### ISSUE TITLE
Ginkgo/MEDUSA

### ISSUE THREAD

**Issue by cpoupon** [bweyers/HBPVisCatalogue#435]
Dear HBP software support team,

I would like to submit the Ginkgo/MEDUSA simulation tool that has been developed in the frame of HBP SGA2 and corresponding to the milestone MS2.6.2 A dictionary of simulated samples mimicking white matter and more specifically to the Task T2.6.5 Simulation and tractography performed on the HPC.
This tool allows to simulate the membrane geometry of brain cellular environments as well as their diffusion MRI signatures.
With best regards,

Cyril
[MetaDataTemplateV2-Medusa.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/5237799/MetaDataTemplateV2-Medusa.xlsx)

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=2063353137

**Comment by jagru20** [comment]
@cpoupon can you please provide a date on which the software has been created and fill it into the spreadsheet in field _B5_ ?

**Comment by jagru20** [comment]
released: https://kg.ebrains.eu/search/?facet_type[0]=Software#Software/91e8f01e-af99-4804-b42d-a08407b86940

**Comment by cpoupon** [comment]
Dear Curation Team,

I modified the create date to 2020, June, 30th
Tell me if it is ok on your side,

All the best,

Cyril

**Comment by jagru20** [comment]
That's fine, thanks. released: https://kg.ebrains.eu/search/?facet_type[0]=Software#Software/91e8f01e-af99-4804-b42d-a08407b86940
