### ISSUE TITLE
Ginkgo/GlobalTractography

### ISSUE THREAD

**Issue by cpoupon** [bweyers/HBPVisCatalogue#436]
Dear HBP software support team,

I would like to submit the Ginkgo/GlobalTractography processing tool that has been developed in the frame of HBP SGA2 and corresponding to the milestone MS2.6.2 A dictionary of simulated samples mimicking white matter and more specifically to the Task T2.6.6 Simulation and tractography performed on the HPC.
This tool allows to infer the structural connectivity of the human brain from diffusion MRI or other imaging dataset providing orientation distribution function maps (PLI, ...)
[MetaDataTemplateV2-GinkgoGlobalTractography.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/5238463/MetaDataTemplateV2-GinkgoGlobalTractography.xlsx)
.
With best regards,

Cyril

**Comment by jagru20** [comment]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=772256348

**Comment by jagru20** [comment]
@cpoupon, could you please have a quick look at the modified spreadsheet at https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=772256348 and give us feedback? If you are fine with the metadata, we will integrate it into the KG.

**Comment by jagru20** [comment]
@cpoupon can you please provide a date on which the software has been created?

**Comment by cpoupon** [comment]
Dear Curation Team, 

The modified google doc is ok for me.
The date of the creation of the code is October 2017
Tell me if it answers your questions.
All the best,

Cyril Poupon

**Comment by jagru20** [comment]
Thanks so far! Actually I was looking for a specific day. Can you provide it?

**Comment by jagru20** [comment]
released: https://kg.ebrains.eu/search/?facet_type[0]=Software#Software/e82f2f4d-82e0-4c0d-bb31-b0ca91ded522
