### ISSUE TITLE
3D Structure Tensor Analysis

### ISSUE THREAD

**Issue by gmazzamuto** [bweyers/HBPVisCatalogue#437]
Dear all,

please find attached the xlsx for the curation of this software.

[3D_STA.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/5246225/3D_STA.xlsx)

Best

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=974309602

**Comment by jagru20** [comment]
@gmazzamuto, please have another look at the modified metadata spreadsheet. If you agree with it, we continue integration.

**Comment by jagru20** [comment]
Is released

**Comment by gmazzamuto** [comment]
Looks good to me, thank you
