### ISSUE TITLE
MB v0.1.0

### ISSUE THREAD

**Issue by JohnAshburner** [bweyers/HBPVisCatalogue#438]
[MetaDataTemplateV2-MB.txt](https://github.com/bweyers/HBPVisCatalogue/files/5267502/MetaDataTemplateV2-MB.txt)

Converted to .txt because .csv not supported here.

**Comment by jagru20** [comment]
@JohnAshburner we have revised and slighty adapted the information as well as added some questions. Please have a look at the spreadsheet 
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1966332817
and use the "Commonts Developer" column for your comments and answers.

**Comment by jagru20** [comment]
released: https://kg.ebrains.eu/search/?facet_type[0]=Software#Software/6b3a113b-8640-4e27-baab-bf4eef1c6501
