### ISSUE TITLE
FIL v0.1.1

### ISSUE THREAD

**Issue by JohnAshburner** [bweyers/HBPVisCatalogue#439]
[MetaDataTemplateV2-FIL.txt](https://github.com/bweyers/HBPVisCatalogue/files/5267711/MetaDataTemplateV2-FIL.txt)

**Comment by jagru20** [comment]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1385068235

**Comment by jagru20** [comment]
@JohnAshburner Can you please have a quick look at the [spreadsheet ](https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1385068235)and add feedback where necessary? Thanks!

**Comment by bweyers** [comment]
has been released!
