### ISSUE TITLE
TVB (The Virtual Brain) 1.5.8

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#44]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=691597696

**Comment by s4safeld** [comment]
Beautifully documented software. As always there are some uncertaintys. But very few, and quite insignificant tbh. See Comment collumn in Data Sheet.

**Comment by FeldNico** [comment]
Developer will be notified soon

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer reminded: 17.03.20

**Comment by FeldNico** [comment]
Developer left comments. please check and integrate

**Comment by s4safeld** [comment]
I finished integrating TVB as far as currently possible.
- note that I added the full list of screenshots and not just the selection I picked for the spreadsheet.
