### ISSUE TITLE
demics

### ISSUE THREAD

**Issue by ericup** [bweyers/HBPVisCatalogue#440]
Dear HBP software support team,

I would like to submit the Demics Python library.
Please note that this software is ought to be curated **by 29.09.2020** to meet the deadline.

With best regards,
Eric

[demics.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/5276947/demics.xlsx)

**Comment by jagru20** [comment]
Dear Eric,

We will curate the library as soon as possible. I hope that you understand that we have limited resources but numerous requests like yours, thus "as soon as possible" means "as soon as our resources allow". However, if you want to make sure that you can meet your deadline for future submissions, I strongly recommend that you submit any software significantly before the deadline (i.e. at least one week in advance, better two or three). Moreover, the more thorough you fill in the template, the less time do we need for curation as it is our responsibility to maintain a minimum level of quality in the metadata we integrate into the knowledge graph.

Nevertheless we will of course do our very best to help you meet your deadline.

Best regards,
Jan

**Comment by ericup** [comment]
Dear Jan,

Thank you very much for your reply, I really apprechiate it! We will keep your words in mind for our next submission.

Best regards,
Eric

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=2114662358

**Comment by herr-zett** [comment]
Hello Eric,

I've created a Google Spreadsheet containing information about your software (see link above). Could you please provide information about the **funder(s)/funding (cell B11)** of this software? Additionally, a short **summary (cell B3)** of one sentence in length about the software would be very helpful; alternatively we could use the description (cell B4) you've provided as a summary, if you're willing to expand on the description.
This would provide us with the minimum information (cells B2-B14) necessary for integration into the Knowledge Graph.

Moreover I've noticed that the latest release on GitHub references [version 0.1.0](https://github.com/FZJ-INM1-BDA/demics/releases/tag/0.1.0), while the filled in template you've provided refers to version 1.0. Will there be a new release published on GitHub in the foreseeable future? This would enable us to fill in cells B18 (Release Notes) and B25 (Source Code) properly.

Thanks in advance and best regards,
Daniel

**Comment by ericup** [comment]
Hello Daniel,

Thank you very much!
A pre-release is now available.
I updated the respective cells accordingly.

Best regards,
Eric

**Comment by jagru20** [comment]
Has been released: https://kg.ebrains.eu/search/?facet_type[0]=Software&q=demics#Software/0ab66f6c-5f4c-48e6-89f5-cdd5193e9e35
