### ISSUE TITLE
ExploreASL 

### ISSUE THREAD

**Issue by jagru20** [bweyers/HBPVisCatalogue#443]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=2049978321 

This software was submitted by Henk Mutsaerts (@ExploreASL)

Please note that we assume all persons named in the metadata form have endorsed the processing and the publication of their names, E-Mail addresses and ORCID in the EBRAINS knowledge graph.

**Comment by HenkMutsaerts** [comment]
Thanks, the publication of the authors' names is fine, this is already in NeuroImage/GitHub where this is public domain.
I saw in your excel table that you categorize ExploreASL as "not-free software", what is the criterion for this? ExploreASL is free for academic usage, only if others earn money with our academic work, we would like to have some of this commercial revenue transferred into academic funding. While we haven't fully written the license yet (I still have to get the lawyers to do this), we are going with an FSL-type of license.

Hope this helps, happy to answer any remaining questions, and thanks for adding ExploreASL to eBrains!
Best wishes,
Henk

**Comment by herr-zett** [comment]
@jagru20 It seems that I have do not have permission to edit the spreadsheet. Could you grant me access for editing?

**Comment by jagru20** [comment]
@HenkMutsaerts The content of the spreadsheet is not final yet. "False" is the default value for the respective field. We will integrate all information we can find and will contact you again to revise it. However, if you want to support us, you are welcome to add and correct information to the spreadsheet yourself, as this speeds up the curation process significantly. If you are interested in a more detailed description of the meta data curation workflow, have a look [here](https://github.com/bweyers/HBPVisCatalogue/wiki/Curation-Workflow#workflow-implementation). 
It could be helpful to inform us when the license is completed. How do you plan to name it? 

Best
Jan

**Comment by HenkMutsaerts** [comment]
Dear Jan,


Thanks, you should probably be able to find all the required information in the ExploreASL neuroimage paper, if not, do you mind asking me the details by email?

The license indeed needs to be finalized, this will be an "academic free" license (very similar to the one from FSL). Can I update the license later, or do you need this before curating?

Many thanks again!
Best wishes,

Henk

**Comment by jagru20** [comment]
Dear Henk, 

thanks for the hint to the paper. If we need more information, I will contact you via email. 
For the license: We can tentatively publish the metadata without any license information and you can use the steps described [here](https://github.com/bweyers/HBPVisCatalogue/wiki/How-to-start-software-meta-data-curation%3F#update-curated-software) to initiate an update process when the license is final. Do you prefer this over waiting with the publication until the license is complete?

All the best

Jan

**Comment by HenkMutsaerts** [comment]
Yes, thanks, this sounds great!

Best wishes,
Henk

**Comment by jagru20** [comment]
Dear @HenkMutsaerts,

we are now finished with collecting metadata for ExploreASL and in our opinion, the data in the spreadsheet is ready for the publication in EBRAINS knowledge graph. Before we do this, I would like you to have another look at it to see if you agree with what is about to be published. Let us now if you have any feedback. 

Thanks and best wishes,

Jan

P.S.: When there is any update for ExploreASL, you can use the [update procedure](https://github.com/bweyers/HBPVisCatalogue/wiki/How-to-start-software-meta-data-curation%3F#update-curated-software) to inform us.

**Comment by jagru20** [comment]
released.

**Comment by HenkMutsaerts** [comment]
Thanks all, and happy 2021!
