### ISSUE TITLE
openMINDS metadata creator

### ISSUE THREAD

**Issue by BrainModes** [bweyers/HBPVisCatalogue#444]
[](https://github.com/bweyers/HBPVisCatalogue/files/5474926/MetaDataTemplateV2_openmindscreator.xlsx)
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1616235979

**Comment by jagru20** [comment]
Thank you for your submission. 
Please note that we assume all persons named in the metadata form have consented to the processing and the publication of their names, E-Mail addresses and ORCID in the EBRAINS knowledge graph.

**Comment by jagru20** [comment]
@BrainModes we have almost finished the curation of openMINDS metadata creator. Before we release the metadata into the knowledge graph, please have a last look at the spreadsheet and let us know, if you agree with the publication as-is or leave change requests in Column D (and comment on this issue when your revision is finished). Thanks!

**Comment by BrainModes** [comment]
Thank you for curating. I made two small changes (Metedata->Metadata | removed "Graphical User Interface") and agree with publication. Thanks!

**Comment by jagru20** [comment]
released.
