### ISSUE TITLE
NEST Desktop Update

### ISSUE THREAD

**Issue by jens-br** [bweyers/HBPVisCatalogue#449]
NEST Desktop is released in version 2.5.0. Could you update the page? For completeness, I included the changes also in the requested document ([Template](https://seafile.rlp.net/f/eabba83e1edf4439a920/)).

**Comment by jagru20** [comment]
https://docs.google.com/spreadsheets/d/1p3At9DXATJeUyeX_cvV_lRv8M54nCLe2F0g8X4PmIgw/edit#gid=0

**Comment by herr-zett** [comment]
@jagru20 @bweyers 
The update includes two new components: NEST Simulator and NEST Server.

While I think that NEST Simulator still refers to issue #20, there's currently no issue regarding NEST Server. Is this a software that needs to be curated and is therefore in need of its own issue?

**Comment by jens-br** [comment]
Since some structural changes were made to NEST Server, maybe [upcoming version of the documentation (pre-release)](https://github.com/sarakonradi/nest-simulator/blob/create_nest_server_page/doc/guides/nest_server.rst) could be of interest.

**Comment by bweyers** [comment]
NEST Server is now a component of NEST Simulator. And NEST Simulator is NEST. Thus, no additional software need to be curated.

**Comment by jagru20** [comment]
released.
