### ISSUE TITLE
DC Explorer 1.0

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#45]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=654282557

**Comment by AnnHa2019** [comment]
No further information can be found. But maybe the developers can give it. They also developed Vishnu, Pyramidal Explorer and Clint Explorer

**Comment by bweyers** [comment]
Should be send for revision!

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer provided information. Please check and integrate

**Comment by AnnHa2019** [comment]
To be released, but additions/changes are still necessary

**Comment by FeldNico** [comment]
released
