### ISSUE TITLE
Arbor 0.5

### ISSUE THREAD

**Issue by jagru20** [bweyers/HBPVisCatalogue#453]
We received an update request for arbor ([KG-Entry](https://search.kg.ebrains.eu/instances/Software/80d205a9-ffb9-4afe-90b8-2f12819950ec)) for their new version 0.5. 

@brenthuisman to keep the update process clean and to make sure all the changes made are correct, I suggest following our [Update procedure](https://github.com/bweyers/HBPVisCatalogue/wiki/How-to-start-software-meta-data-curation%3F#update-curated-software). for this, I prepared a google spreadsheet ([link](https://docs.google.com/spreadsheets/d/1tVP3bymEW-EzIMAlpddSFvr4UVlW6eOtuHZ5I-VZtWY/edit?usp=sharing)) which is by now only a copy of the spreadsheet for Arbor 0.2.2. please change the information that is to be changed and mark the changes (As I have done it exemplarily for the Name). We will then integrate it into EBRAINS. Thank you!

Please feel free to contact us here or via E-Mail in case you have questions or comments. You can also use the comment-columns in the spreadsheet.

**Comment by brenthuisman** [comment]
@jagru20 Thanks, I couldn't find an update procedure on the KG itself!

Since I couldn't update the Google doc, please see the speadsheet attached. Update are with blue background and/or red text.
[Arbor v0.5.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/5787455/Arbor.v0.5.xlsx)

I think that's all, if not let me know :)

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=437840375

@jagru20 I've copied the information provided by the developer into a new spreadsheet (link above) that should be alterable by everyone who has access to the link. Additionally, I've updated cell B31 (Software Features) to include data types.

**Comment by brenthuisman** [comment]
Thanks, made a tiny update to B31.

**Comment by jagru20** [comment]
released
