### ISSUE TITLE
oneAPI Threading Building Blocks (oneTBB) 2021.1.1

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#454]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=75137396

Update of "Threading Building Blocks 2019 Update 9"
(KG Nexus-ID: softwarecatalog/software/software/v1.0.0/757b254e-eb6a-4789-9572-95e69e345467)

**Comment by jagru20** [comment]
@herr-zett please migrate the spreadsheet to openMINDS

**Comment by jagrue** [comment]
released
