### ISSUE TITLE
Frites 0.3.7

### ISSUE THREAD

**Issue by jagru20** [bweyers/HBPVisCatalogue#457]
Please integrate `Frites 0.3.7`

https://docs.google.com/spreadsheets/d/15fZnUsMmNZdUHpoj5cJp6C_FUexWjy212TmPrK01J5E/edit?usp=sharing

**Comment by brovelli** [comment]
Dear all,
I have finished updating the information about Frites into the spreadsheet xls file. 
Best,
Andrea

**Comment by EtienneCmb** [comment]
Actually, the latest version is not `0.3.7` but `0.3.8`. We modified the spreadsheet accordingly.

Thank you in advance,

Best,
Etienne

**Comment by jagru20** [comment]
@EtienneCmb @brovelli Thank you for providing the information. Please note that we assume all persons named in the metadata form have endorsed the processing and the publication of their names, E-Mail addresses and ORCID in the EBRAINS knowledge graph. 
In the frites GitHub repository is mentioned another contributor, is he not mentioned as an author in the spreadsheet on purpose?
A side note: In the initial request you stated, that you are about to publish a paper about Frites. Once it is published, feel free to directly open an Issue to update the KG-entry.

**Comment by brovelli** [comment]
Dear @jagru20 ,
As soon as we will have a biorxiv preprint, we will share it.
Concerning the 3rd contributor Ruggero Basanisi, there is no real reason. He is a PhD student in my group, but he will finish his PhD this year. Shall we add him as well? 
The main developer is Etienne Combrisson @EtienneCmb

**Comment by jagru20** [comment]
Dear @brovelli,
actually we only list digital identifiers, not files. So just let us know which DOI, RRID or similar identifier you want to register as the publication related to this software.
For the third contributor: Most of the time, we list all persons that contributed to the software unless there is a specific reason, not to do so. As I do not know if there is such a reason from your side, I just wanted to make sure we don't miss something by accident. Long story short: In the end, the decision on who is listed as an author is up to you, I am just double-checking.

**Comment by EtienneCmb** [comment]
Dear @jagru20,

Actually the list of contributors extend to more than three peoples (see [here](https://brainets.github.io/frites/community.html#authors-and-contributors) the complete list). But for authors, I would say that it's mainly Andrea and I.

**Comment by brovelli** [comment]
The DOI will be fine. 
Sorry for the naive question, but do **we** have to request a DOI or are you going to do it?

**Comment by jagru20** [comment]
@EtienneCmb So then we keep the two of you in the list. 
Regarding the DOIs: I think I was a bit unclear at that point. What I wanted to ask for was that you tell us the Identifier (which could for example be a DOI) that you receive from the place where you publish the paper.

I try to differentiate this a bit more cleary. We need to distinguish between two different DOIs: 
1. The DOI for the publication in which you reference the software is usually assigned by the journal and identifies the corresponding paper. However, this DOI can be displayed in the knowledge graph. (Taken from B17 of the spreadsheet)
2. A DOI that refers to the metadata entry in the knowledge graph would be registered by EBRAINS. This functionality is currently not available, but will be after the migration to the new metadata standard openMINDS at the earliest.

If you would like to receive a DOI for the metadata entry, we can note this now and create the DOI as soon as the functionality is available.

**Comment by brovelli** [comment]
OK, I get it. 
1. Publication DOI: we will send you the DOI of the associated paper as soon as we get it from the publisher.
2. Metadata DOI: yes please, I'd like to receive it.

Thanks

**Comment by jagru20** [comment]
released: https://search.kg.ebrains.eu/instances/Software/453d65d6-1b12-4db2-93f0-f0b8f68da0f3?group=curated
