### ISSUE TITLE
Viziphant

### ISSUE THREAD

**Issue by mdenker** [bweyers/HBPVisCatalogue#461]
[Template_openMINDS_Visiphant.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6149237/Template_openMINDS_Visiphant.xlsx)

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/1DAhLSbI6-pgFhGv1vD8ALbfT5uaMHdGKoj25JJyNiqU/edit#gid=530396787

Updated the spreadsheet to match openMinds v2.0.0

**Comment by jagru20** [comment]
Dear @mdenker, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1DAhLSbI6-pgFhGv1vD8ALbfT5uaMHdGKoj25JJyNiqU/edit#gid=530396787), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by jagru20** [comment]
@mdenker, just a kind reminder to give us the "go" for publishing your metadata on viziphant.

**Comment by mdenker** [comment]
I think that looks good all in all.

Not quite sure if it makes sense to list all emails and github accounts here, to be honest -- but of course, I assume you have guidelines in place.

**Comment by herr-zett** [comment]
Instance added to the KG
