### ISSUE TITLE
Brainstorm

### ISSUE THREAD

**Issue by ftadel** [bweyers/HBPVisCatalogue#462]
[Template_openMINDS_brainstorm.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6183209/Template_openMINDS_brainstorm.xlsx)

**Comment by jagru20** [comment]
@ftadel We need to enter a Version Identifier (e.g., 1.0.0) to specify, what state of the software was used to integrate its metadata into the knowledge graph. I strongly recommend establishing (pre-)release labels in the github repository. However, if there is no version number or such, we will use the date of the day we integrate the metadata into the knowledge graph. I just want you to be aware of this.

**Comment by ftadel** [comment]
> However, if there is no version number or such, we will use the date of the day we integrate the metadata into the knowledge graph

This is correct: this is how we identify the versions of the software (same as FieldTrip).

![image](https://user-images.githubusercontent.com/6920058/113701718-ceb4f480-96d8-11eb-8251-e3fcf30df983.png)

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/1c2ARRkJmymMDOtjfP4ELLQ0QPU9GdWykrMc0Qf6Ykpc/edit#gid=154442664

**Comment by jagru20** [comment]
Dear @ftadel, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1c2ARRkJmymMDOtjfP4ELLQ0QPU9GdWykrMc0Qf6Ykpc/edit#gid=154442664), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by ftadel** [comment]
Please remove Martin Cousineau from the authors, he's not part of the development team anymore.

Note that we don't recommend using outdated versions (the one you included is from July 2021...) and we won't provide support for it.
Just like FieldTrip, we don't distribute "stable" versions of the software - the latest is always supposed to be the best/recommended.

**Comment by jagru20** [comment]
>Note that we don't recommend using outdated versions (the one you included is from July 2021...) and we won't provide support for it.

I do not know FieldTrip, but we are not curating outdated versions, we are curating metadata on that version that a developer provides us in their curation request. As I mentioned in one of the comments above: If there is no version number provided like in this case, we use the point in time when we release the Knowledge Graph entry to public as a version Identifier. That suits such cases quite well. I see that you omit the process of versioning on your side which might make development faster and easier for you as you do not need to maintain more than the last commit on your main branch. However, we do not have the resources available to keep track of every commit that you make to your repository. This is why we link to your repository, where any user gets the actual latest software from. It would be feasible to explicitly mention this in the description to avoid misunderstandings. 

> I think the entry "version innovation" doesn't make much sense.

If this would not make sense, why would you establish this page then: https://neuroimage.usc.edu/brainstorm/Updates ? The property "version innovation" carries information on how to find what the latest changes in that software are. 

So, to proceed with this, here is what we will do: 

- We integrate the information in the above mentioned spreadsheet alongside with the date at which we integrated it. 
- We add the sentence "**Any time you want to use Brainstorm, be sure to pull the latest version from their GitHub Repository first.**" in bold to the description. 
- Whenever there is a substantial change in brainstorm that affects the information that is curated in the KG, you reach out to us for an update and we will then change the information. For example a member leaving the development team would be such a change. 

Are you happy with this?

**Comment by ftadel** [comment]
> If this would not make sense, why would you establish this page then: https://neuroimage.usc.edu/brainstorm/Updates ?

I'm not sure I understand what the logic is to document the update description of one random time point in your knowledge graph if you ask your users to update Brainstorm. It feels to me like documenting a software by the last commit message.
Can you set this "version innovation" field to the URL instead: https://neuroimage.usc.edu/brainstorm/Updates?

> We integrate the information in the above mentioned spreadsheet alongside with the date at which we integrated it.

I can't comment on this, as it is dependent only on your local way to distribute/document software.

> We add the sentence "Any time you want to use Brainstorm, be sure to pull the latest version from their GitHub Repository first." in bold to the description.

We don't recommend pulling Brainstorm from the GitHub repo, but rather download it once from the Brainstorm website, and then using the update features of the software (automatically or manually):
https://neuroimage.usc.edu/brainstorm/Installation#Updates

Even if we don't have the resource necessary to manage stable releases (I'm the only person managing all this), there might be some lag between the github commit and the package available for download on the Brainstorm website.
Feel free to document this the way that you feel is the most adapted to your users.

> Whenever there is a substantial change in brainstorm that affects the information that is curated in the KG, you reach out to us for an update and we will then change the information. 

The software is evolving continuously, it is deployed in hundreds of research labs worldwide, and unfortunately we don't have the resource to monitor the documentation each individual installation. Whatever you feel is not going to be documented correctly: replace the actual information to a URL to our resources.

> For example a member leaving the development team would be such a change.

For example, replace the names of the developers with the URL describing our development team:
https://neuroimage.usc.edu/brainstorm/AboutUs

**Comment by jagru20** [comment]
> Can you set this "version innovation" field to the URL instead: https://neuroimage.usc.edu/brainstorm/Updates?

Of course! Actually I already did this before writing the previous comment. I got you wrong at this point. You meant the value in field B29 whereas I thought you meant versionInnovation in general. 

> We don't recommend pulling Brainstorm from the GitHub repo, but rather download it once from the Brainstorm website, and then using the update features of the software (automatically or manually):
https://neuroimage.usc.edu/brainstorm/Installation#Updates

Alright, I did not know about that possibility. We will reference that then, of course.

> For example, replace the names of the developers with the URL describing our development team:
https://neuroimage.usc.edu/brainstorm/AboutUs

I get the idea and this sounds totally sensible. However, we need to stick to the [openMINDS specification ](https://humanbrainproject.github.io/openMINDS/v2/core/v3/products/software.html) here, which entails that we cannot add a plain link as the value of the property "developer". But what we could do instead: Enter an [organisation as developer](https://humanbrainproject.github.io/openMINDS/v2/core/v3/actors/organization.html) which then can hold  https://neuroimage.usc.edu/brainstorm/AboutUs as value of the property "homepage". Question is: What organisation would be sensible to mention here? I would suggest a name like "Brainstorm Team" although this is not an organisation that is registered somewhere, this still describes best what it should describe, right?

**Comment by ftadel** [comment]
> But what we could do instead: Enter an organisation as developer which then can hold https://neuroimage.usc.edu/brainstorm/AboutUs as value of the property "homepage". Question is: What organisation would be sensible to mention here? I would suggest a name like "Brainstorm Team" although this is not an organisation that is registered somewhere, this still describes best what it should describe, right?

Sounds good to me!

**Comment by herr-zett** [comment]
Instance has been added to the KG. Some file formats have to be added to the KG as ContentTypes according to the openMINDS schema first, before they can be added to this instance of the software as input and output formats. This will happen automatically once they have been created.
