### ISSUE TITLE
Formats specification/examples lacking for attribute descriptions

### ISSUE THREAD

**Issue by Helveg** [bweyers/HBPVisCatalogue#463]
There are no specific formats specified for the attributes listed [here](https://github.com/bweyers/HBPVisCatalogue/wiki/Attribute-Descriptions). Some examples are dates: DD-MM-YYYY, DD/MM/YYYY? Or multiple values: are we allowed to specify multiple values, comma separated, one on each line .. ?

A non-exhaustive list of attributes where I had difficulty with the format:

* `Digital Identifier`: is this a DOI, URI, ... ?
* `Has Component`: same thing, this needs to be some HBP/EBRAINS recognized thing?
* `Release Date`
* `Funding`: open format or do we have to specify  grant numbers?

**Comment by jagru20** [comment]
Dear @Helveg,

thanks for pointing to these issues. Some further information on the formats are given in the links in the respective cell containing the name of the property. This links to the [openMINDS documentation](https://humanbrainproject.github.io/openMINDS/core/schemas/v3/products/softwareVersion.html). As stated in one of my previous mails, this is still subject to change but can be used as a reference for now. To address your specific cases: 

- `Digital Identifier` can be a DOI or a link to SWHID (e.g., [swh:1:snp:bf175a6f37b841b1e76fa3a344d6261b06737e15](https://archive.softwareheritage.org/swh:1:snp:bf175a6f37b841b1e76fa3a344d6261b06737e15/)) note that this is not mandatory anymore.
- `Has Component` relates to other software entities that are either already integrated in the knowledge graph or should be integrated soon.
- `Release Date` is the simple date of the latest release. Preferably in DD-MM-YYYY, but we will double-check that anyway.
- `Funding` Please provide the funding organisation and grant numbers here. 

In general, all of this information is reviewed and double-checked by our team, so we will come back to you if we encounter any other ambiguities. However, we will adapt the documentation in the wiki and the excel sheet to avoid such confusion in the future. 

Best,

Jan
