### ISSUE TITLE
Brain Scaffold Builder

### ISSUE THREAD

**Issue by Helveg** [bweyers/HBPVisCatalogue#464]
[Template_openMINDS (1).xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6222995/Template_openMINDS.1.xlsx)

**Comment by herr-zett** [comment]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1xysVas96ABFENTR8pk5uvyvZAke1dKGpEYj6T5aHqdU/edit#gid=1978094444) according to the current openMINDS v2 scheme.

**Comment by jagrue** [comment]
released e3c059b1-cb00-417c-8802-046ff532273a
