### ISSUE TITLE
LFPy v2.2.1

### ISSUE THREAD

**Issue by espenhgn** [bweyers/HBPVisCatalogue#465]
[Template_openMINDS.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6262785/Template_openMINDS.xlsx)

**Comment by PatriziaDuhr** [comment]
Spreadsheet: https://docs.google.com/spreadsheets/d/1cSAWbnXAw2aKfQgfM67upn22T0P_D5WfJQlx9mQ3DC0/edit?usp=sharing

**Comment by jagru20** [comment]
Dear @espenhgn, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1cSAWbnXAw2aKfQgfM67upn22T0P_D5WfJQlx9mQ3DC0/edit?usp=sharing), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by espenhgn** [comment]
Hi. Please proceed with the process.

**Comment by herr-zett** [comment]
Dear @espenhgn, the integration of your software is about to be completed. To finish the process, additional information about the software's funding (cell B22 in the [spreadsheet](https://docs.google.com/spreadsheets/d/1cSAWbnXAw2aKfQgfM67upn22T0P_D5WfJQlx9mQ3DC0/edit?usp=sharing)) is needed. This concerns the following entries:
- International Neuroinformatics Coordinating Facility
- BrainScaleS

To be able to add these fundings, the following information is required:
- _Award number_
- _Award title_
- _Funder_

Is it possible for you to provide this information?

For the funder "Research Council of Norway" the following information could be found ([source](https://prosjektbanken.forskningsradet.no/en/project/FORISS/250128?Kilde=FORISS&distribution=Ar&chart=bar&calcType=funding&Sprak=no&sortBy=date&sortOrder=desc&resultCount=30&offset=0&Fritekst=LFPy)):
- _Award number_: 250128
- _Award title_: COmputing BRAin signals (COBRA): Biophysical computations of electrical and magnetic brain signals
- _Funder_: Research Council of Norway

If this information is not correct, please let us know what should be added instead.

Thank you in advance!

**Comment by espenhgn** [comment]
Hi. For BrainScaleS we have 
Award number: 269912
Award title: BrainScaleS
Funder: European Union Seventh Framework Programme (EU) 

For INCF we have: 
Award number: 269774
Award title: The Norwegian Node of the International Neuroinformatic Coordinating Facility
Funder: Research Council of Norway

The COBRA project (# 250128) details look correct to me.

**Comment by herr-zett** [comment]
Thank you for providing the missing information! The instance of your software has been released.

**Comment by espenhgn** [comment]
Hi @herr-zett or whoever this concerns. 
Something is not right with the release on the KG at https://search.kg.ebrains.eu/instances/2ebb6f71-6ea9-43b6-bfb0-17ecfb23e168 

The title "LFPy" and short description is missing altogether. Nothing shows except an empty white bar after searching for LFPy: https://search.kg.ebrains.eu/?facet_type[0]=Software&q=LFPy

Also, I have a question. How do you manage different releases? What is on there is now version 2.2.1, which since the start of this curation process has been superseded by two newer releases (versions 2.2.2, 2.2.3). Surely, there should be some way of automatically update the entry whenever I create releases on Github/PyPI instead of manual curation like so: https://github.com/bweyers/HBPVisCatalogue/issues/489?

@torbjone FYI.

**Comment by jagru20** [comment]
I will have a look why the information is not displayed, thanks for pointing this out. 

Regarding the updates: unfortunately we do not have the opportunity to let KG entries be updated automatically. Whenever you want an entry updated, let us know and especially point out what has changed in comparison to the previous version. We then create an additional entry for that version. Att versions should then be displayed summarized in the KG card.

**Comment by jagru20** [comment]
Ok, for the missing information: Please have another look at the search, it should be complete now.

**Comment by espenhgn** [comment]
Thanks, the title etc. is indeed in place. 

But I now noticed another issue; the entry with a url "Cite software
DOI: 10.5281/zenodo.4014889" points to https://search.kg.ebrains.eu/instances/2ebb6f71-6ea9-43b6-bfb0-17ecfb23e168 but this DOI url should point to https://doi.org/10.5281/zenodo.4014889

**Comment by jagru20** [comment]
This is a KG issue, I forwarded it and it will hopefully be fixed soon.

**Comment by espenhgn** [comment]
Hi again, @jagru20 . Sorry, I should have spotted this earlier. The software title at https://search.kg.ebrains.eu/instances/2ebb6f71-6ea9-43b6-bfb0-17ecfb23e168 reads "Local Field Potentials in Python" but this should be "LFPy". Can you fix, please?

**Comment by jagru20** [comment]
The reason it reads "Local Field Potentials in Python" is because we have this as Full name. The Full name is Supposed to give a little more info if otherwise an acronym is used. Thus, I changed it to "LFPy - Local Field Potentials in Python" I will contact the KG development team to see if we can display the short name in another way. Let me know if you are absolutely unhappy with this.

**Comment by espenhgn** [comment]
Ok, these naming conventions on the KG are applied entirely inconsistently, in particular for software. On one end you have the "Electrophysiology Analysis Toolkit" listed as "Elephant" (which I presume most refer to this package as) and "NEST" listed as "The Neural Simulation Tool" (which I presume no one refers to it as anymore), etc. 

In the particular case of LFPy, I would say "Local Field Potentials in Python" is no longer fully descriptive of the capabilities of this package. Please just use "LFPy" which is what we refer to it as, and is also used in related tools that remains to be added to the KG (namely LFPykit; LFPykernels; hybridLFPy)

**Comment by jagru20** [comment]
In fact, the full name for Elephant should be "Electrophysiology Analysis Toolkit" thanks for pointing to this. The reason for this is that "Elephant" for that instance is listed as fullName. However, the decision wether a name is a full name or not from the openMINDS perspective is if the phrase uses acronyms or not. LFPy, Elephant and NEST are acronyms or abbreviations and therefore not full names (according to the [metadata schema](https://humanbrainproject.github.io/openMINDS/v3/core/v4/products/software.html), also linked in the excel template). I see the point that you do not think someone refers the software by their full name and thus want the short name displayed on the software card. This is why I mentioned contacting the KG development team to display it differently i.e., the short name instead of the fullName.
