### ISSUE TITLE
COMPSs 2.9

### ISSUE THREAD

**Issue by rsirvent** [bweyers/HBPVisCatalogue#466]
[Template_openMINDS_COMPSs.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6277745/Template_openMINDS_COMPSs.xlsx)

**Comment by jagru20** [comment]
related to #89

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/12ARVXD0G5EPHeUuIPtxUQKTpFRW5oVfIpCzDOuhG-F4/edit#gid=1907381003
(new spreadsheet that matches the structure of openMINDS v2)

Updated to version 2.9

**Comment by jagru20** [comment]
Dear @rsirvent, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/12ARVXD0G5EPHeUuIPtxUQKTpFRW5oVfIpCzDOuhG-F4/edit#gid=1907381003), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by jagru20** [comment]
COMPSS is now registered in the KG: https://search.kg.ebrains.eu/instances/bd929e78-07b8-4987-a3bb-01a6375a780c
