### ISSUE TITLE
morphIO v3.3.0

### ISSUE THREAD

**Issue by alex4200** [bweyers/HBPVisCatalogue#468]
[Template_morphio.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6301487/Template_morphio.xlsx)

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/11tl0dynCAOmkgZYQGQL0JB6FBGGE8t_2u-tSXC6NDkg/edit#gid=444554846
(new spreadsheet that matches the structure of openMINDS v2)

**Comment by jagru20** [comment]
Dear @alex4200, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/11tl0dynCAOmkgZYQGQL0JB6FBGGE8t_2u-tSXC6NDkg/edit#gid=444554846), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by jagru20** [comment]
released: https://search.kg.ebrains.eu/instances/5e4d4054-f05b-434a-8b09-6b1ef5d8d968
