### ISSUE TITLE
neurom

### ISSUE THREAD

**Issue by alex4200** [bweyers/HBPVisCatalogue#469]
[Template_neurom.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6301526/Template_neurom.xlsx)

**Comment by PatriziaDuhr** [comment]
Spreadsheet: https://docs.google.com/spreadsheets/d/1bZrOGSz0fe0hSgHIwir47Bvuyrve0wjrCUcaIXW8sMY/edit?usp=sharing

**Comment by jagru20** [comment]
Dear @alex4200, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1bZrOGSz0fe0hSgHIwir47Bvuyrve0wjrCUcaIXW8sMY/edit?usp=sharing), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by alex4200** [comment]
Hello @jagru20 , the info for neurom in the spreadsheet has been updated and seems to be up-to-date.

**Comment by herr-zett** [comment]
Integration is about to be completed. Currently, the KnowledgeGraph is still missing content types for the file formats SWC and SVG. As soon as they are added, the integration can be completed.

**Comment by herr-zett** [comment]
Instance has been released. File formats SWC and SVG will be added later.
