### ISSUE TITLE
Scalasca 2.5

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#47]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1560942488

**Comment by herr-zett** [comment]
In the [User Guide](https://apps.fz-juelich.de/scalasca/releases/scalasca/2.5/docs/UserGuide.pdf) it is stated that Scalasca can process files in the "CUBE4" format. However, the provided code snippets within the User Guide only mention ".cubex" files.
By which name should this format be listed?

**Comment by FeldNico** [comment]
Score-P, Cube (GUI) are only optional -> removed
Feature Provenence removed

Developer will be notified soon

**Comment by FeldNico** [comment]
Developer Email sent: 24.02.2020

**Comment by herr-zett** [comment]
Given the updated list of software features: Should "Profiling" be added as a feature of Scalasca?

**Comment by bweyers** [comment]
Yes, please add!

**Comment by FeldNico** [comment]
Developer provided informations. Please check.

**Comment by herr-zett** [comment]
Processed developer comments.

Added new questions.

The developer her-/himself posed a question regarding Output Formats

**Comment by FeldNico** [comment]
added few comments. if no further questions please integrate.

**Comment by FeldNico** [comment]
released
