### ISSUE TITLE
morph-tool

### ISSUE THREAD

**Issue by alex4200** [bweyers/HBPVisCatalogue#471]
[Template_morphtool.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6301609/Template_morphtool.xlsx)

**Comment by jagru20** [comment]
Dear @alex4200, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1mfRptdmN09Be791fqisvHC6kK2J3lApOKDZG5wll_lw/edit?usp=sharing), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by alex4200** [comment]
Hello @jagru20, the info for morph-tool in the spreadsheet has been updated and seems to be up-to-date.

**Comment by herr-zett** [comment]
Currently the ContentType for SWC files is missing in the KG. Once it is added to the KG, the integration of MorphTool can be finalised.

**Comment by jagru20** [comment]
@herr-zett please proceed with the integration and add the SWC ct to the list of contenttypes that need to be created. We will add them later to the existing instance.

**Comment by herr-zett** [comment]
Proceeded as suggested by @jagru20

**Comment by jagru20** [comment]
released
