### ISSUE TITLE
IntrAnat

### ISSUE THREAD

**Issue by manikbh** [bweyers/HBPVisCatalogue#472]
[Template_openMINDS_IntrAnat.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6326209/Template_openMINDS_IntrAnat.xlsx)

**Comment by herr-zett** [comment]
[Spreadsheet according to openMINDS v2.0.0](https://docs.google.com/spreadsheets/d/1HsB25l9KhPweBd9kl1LQfpPY4Ej3PKBrvaOe10G0CuI/edit#gid=516196152)

**Comment by jagru20** [comment]
Dear @manikbh, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1HsB25l9KhPweBd9kl1LQfpPY4Ej3PKBrvaOe10G0CuI/edit#gid=516196152), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by manikbh** [comment]
I don't have access to the spreadsheet.

**Comment by manikbh** [comment]
Thank you, no comments were requiring an answer from me and information is still valid.

**Comment by herr-zett** [comment]
Instance has been added to the KG.

**Comment by jagru20** [comment]
@manikbh as far as I understand from [this document ](https://github.com/IntrAnatSEEGSoftware/IntrAnat/blob/brainvisa_4.6/doc/user_documentation.pdf) IntrAnat Electrodes in fact does have output formats (.pts, .txt, .csv) other than mentioned in the spreadsheet. Can you comment on this?

**Comment by manikbh** [comment]
IntrAnat has an export function that exports electrode locations in multiple formats used by external software such as .pts, .txt. and csv for BIDS-compatible storage.

**Comment by jagrue** [comment]
released https://search.kg.ebrains.eu/instances/f9910139-c184-4d03-b103-a0042083153f
