### ISSUE TITLE
 hal-cgp v0.3.0

### ISSUE THREAD

**Issue by Visabado** [bweyers/HBPVisCatalogue#474]
[Template_openMINDS_hal-cgp_26042021.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6377191/Template_openMINDS_hal-cgp_26042021.xlsx)

**Comment by jagru20** [comment]
Dear @Visabado, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1UhpepYdEbeKBekKoTBm69ZKvImFAC929ZDa-D1GnrE0/edit#gid=854414535), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by jagru20** [comment]
@Visabado please review the [spreadsheet ](https://docs.google.com/spreadsheets/d/1UhpepYdEbeKBekKoTBm69ZKvImFAC929ZDa-D1GnrE0/edit?usp=sharing)so that we can continue integration.

**Comment by Visabado** [comment]
Dear Jan,

Looks good thanks.

Best regards,

Virginie

**Comment by herr-zett** [comment]
Instance has been added to the KG
