### ISSUE TITLE
dopp v0.0.1

### ISSUE THREAD

**Issue by Visabado** [bweyers/HBPVisCatalogue#475]
[Template_openMINDS_dopp_26042021.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6377022/Template_openMINDS_dopp_26042021.xlsx)

**Comment by jagru20** [comment]
Dear @Visabado, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1TItxGx0oRyAx6zyIX0O5KygPb1GMGX7OCkkNlQsKXOs/edit?usp=sharing), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by jagru20** [comment]
@Visabado did you check upon the information and comments in the [spreadsheet](https://docs.google.com/spreadsheets/d/1TItxGx0oRyAx6zyIX0O5KygPb1GMGX7OCkkNlQsKXOs/edit?usp=sharing) ? especially the description needs to be extended before we can publish the metadata about dopp.

**Comment by jagru20** [comment]
released https://search.kg.ebrains.eu/instances/15c98b90-c4a3-4fb5-a070-dd43a4c49cb7
