### ISSUE TITLE
NEAT v0.9.1

### ISSUE THREAD

**Issue by Visabado** [bweyers/HBPVisCatalogue#476]
[Template_openMINDS_NEAT.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6450467/Template_openMINDS_NEAT.xlsx)

**Comment by jagru20** [comment]
Dear @Visabado, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1VmPLk8GlEfCbKinByoD28w71rAE6gceDz5pHw4j2Rn0/edit?usp=sharing), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet.
_**Please do not forget to let us know when you finished revising the data.**_
Thank you in advance!

**Comment by herr-zett** [comment]
@jagru20 instance has been integrated so far. Among others, [AMPL](https://www.wikidata.org/wiki/Q295250) is listed as a programming language used for the software. Currently, AMPL is not integrated as a controlled term in the KG. The following JSON-LD can be used for its integration:

```
{
  "@id": "https://openminds.ebrains.eu/controlledTerms/programmingLanguage/AMPL",
  "@type": "https://openminds.ebrains.eu/controlledTerms/ProgrammingLanguage",
  "name": "AMPL",
  "definition": null,
  "description": null,
  "ontologyIdentifier": "https://www.wikidata.org/wiki/Q295250"
}
```

**Comment by jagru20** [comment]
I prepared a pull request for the controlledTerms repository. As soon as it is through, I'll add the missing information and release the instance.

**Comment by jagrue** [comment]
released https://search.kg.ebrains.eu/instances/53d7a160-31ae-4d2a-9250-c90a3d00e2ea
