### ISSUE TITLE
fastpli v1.1.0

### ISSUE THREAD

**Issue by fmatuschke** [bweyers/HBPVisCatalogue#477]
Hi, I have updated the spreadsheet to the new version release
https://docs.google.com/spreadsheets/d/1i3RtJ0tIUV3zK5JUC5SoEH1s_i7kbIn1gp_PzJcuwCA/edit?usp=sharing

**Comment by herr-zett** [comment]
Adopted changes in a new [Spreadsheet](https://docs.google.com/spreadsheets/d/1TSWLTSf6iHHIvOVt75FoZgW6yll0S96XI2tENoEJmmM/edit#gid=1893637458) that follows the [openMINDS v2.0.0](https://humanbrainproject.github.io/openMINDS/v2.0.0/) standard

**Comment by jagru20** [comment]
Dear @fmatuschke, we have checked on the metadata you provided and collected it in a [spreadsheet](https://docs.google.com/spreadsheets/d/1TSWLTSf6iHHIvOVt75FoZgW6yll0S96XI2tENoEJmmM/edit#gid=1893637458), alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet. 
**_Please do not forget to let us know when you finished revising the data._** 
Thank you in advance!

**Comment by jagru20** [comment]
released
