### ISSUE TITLE
Snudda 1.1

### ISSUE THREAD

**Issue by Hjorthmedh** [bweyers/HBPVisCatalogue#478]
Upcoming release of Snudda 1.1

[](https://github.com/bweyers/HBPVisCatalogue/files/6508399/Template_openMINDS_Snudda-1.1.xlsx)
[Spreadsheet](https://docs.google.com/spreadsheets/d/1rJigjXduSdPVHPo1K-7TaTaW7gZkIJfs8vzKKfAOKzc/edit#gid=1423678363)

**Comment by jagru20** [comment]
@Hjorthmedh Snudda is now released. The link to the KG instance will be: https://search.kg.ebrains.eu/instances/8eb5c915-a398-4947-80b1-e1783e36d5b9 
Please be aware, that this link is not active, until the software migration is done. However, you can still use this link for reports.
