### ISSUE TITLE
Subcellular WebApp v1

### ISSUE THREAD

**Issue by dkeller9** [bweyers/HBPVisCatalogue#479]
[Template_openMINDS_webapp.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/6538753/Template_openMINDS_webapp.xlsx)

**Comment by herr-zett** [comment]
Adopted changes in a new [Spreadsheet](https://docs.google.com/spreadsheets/d/1jgqr2TAmzt9zCM_aChBnZe6saaxtnu2-mYtkQbyOJI4/edit#gid=611727285) that follows the [openMINDS v2.0.0](https://humanbrainproject.github.io/openMINDS/v2.0.0/) standard

**Comment by jagru20** [comment]
Dear @dkeller9, we have checked on the metadata you provided and collected it in a spreadsheet, alongside some comments. We are now about to integrate your data into the EBRAINS Knowledge Graph, so please double-check if all information is correct and complete. We might come back to you in the near future to ask about the specification of input or output formats, if we do not have them in our repertoire yet. 
**_Please do not forget to let us know when you finished revising the data._** 
Thank you in advance!

**Comment by dkeller9** [comment]
Hello,

I wanted to check on the integration of this tool into the knowledge graph.
There were a couple of fields that needed to be resolved but I think they
are complete now.

https://docs.google.com/spreadsheets/d/1jgqr2TAmzt9zCM_aChBnZe6saaxtnu2-mYtkQbyOJI4/edit#gid=611727285

Thank you,

Daniel Keller

**Comment by jagru20** [comment]
Dear Daniel, 

thanks for your revision. I integrated the metadata as far as possible into the KG. To curate all input/output formats correctly, could you pleas provide specifications for the following formats: 

BNGL
eBNGL
SBML
NFSim (.rnf)
PySB


Thanks in advance!

Jan

**Comment by jagru20** [comment]
released for now, missing contenttypes will be given later, after developer provided specifications.

**Comment by dkeller9** [comment]
Dear Jan,

The specifications are as given on the following websites:

BNGL (.bngl): https://bionetgen.org/
SBML (.sbml): https://sbml.org/
NFSim (.rnf): http://michaelsneddon.net/nfsim/
PySB (.sbml): https://pysb.org/

Is there a particular format needed for this specification?

Thank you,

Dan

**Comment by jagru20** [comment]
Thank you for the links! I do not need any specific format for now, I will come back to you if I need further information. 

Best 

Jan
