### ISSUE TITLE
RTNeuron 3.0

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#48]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=2066130431

**Comment by FeldNico** [comment]
Display: Virtual Reality removed
Display: Tiled VIdeo Wall added

Developer will be notified soon

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Sent to another Developer as email was invalid

**Comment by FeldNico** [comment]
Developer reminded: 17.03.20

**Comment by herr-zett** [comment]
#137 has been closed due to discontinuation of funding after SGA1.
What about this issue, then?

**Comment by bweyers** [comment]
The software is still highly relevant and should be integrated into KG.

**Comment by bweyers** [comment]
Please integrate.

**Comment by bweyers** [comment]
Software released.
