### ISSUE TITLE
New version of the Nutil Software v0.7.0

### ISSUE THREAD

**Issue by Majpuc** [bweyers/HBPVisCatalogue#485]
Hi,

We have a new version https://docs.google.com/spreadsheets/d/1rwiraz0yZsNgt8cd24_pXypSRvSMJr3nvsURQUkJF0M/edit?usp=sharing

Thanks!

**Comment by Majpuc** [comment]
@jagru20 could you update Nutil?, we need this for the review. Thanks!

**Comment by jagru20** [comment]
@Majpuc updated!
