### ISSUE TITLE
Update metadata about QuickNII v2.2

### ISSUE THREAD

**Issue by Majpuc** [bweyers/HBPVisCatalogue#487]
Dear sw curation team,
We have updated our user documentation. Great if you could release this very soon.

[https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=580454972]
(https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=580454972)

**Comment by jagru20** [comment]
Dear Maja, we will update this as soon as we can, but please be aware, that this will become visible when the software migration is completed.

**Comment by jagru20** [comment]
released
