### ISSUE TITLE
Elephant 0.8.0, 0.9.0, 0.10.0

### ISSUE THREAD

**Issue by mdenker** [bweyers/HBPVisCatalogue#489]
Hi, 

there are 3 updates to Elephant that should be added to extend the current entry for Elephant 0.7.0:
**0.8.0**
https://elephant.readthedocs.io/en/v0.8.0/release_notes.html
https://elephant.readthedocs.io/en/v0.8.0/authors.html
**0.9.0**
https://elephant.readthedocs.io/en/v0.9.0/release_notes.html
https://elephant.readthedocs.io/en/v0.9.0/authors.html
**0.10.0**
https://elephant.readthedocs.io/en/v0.10.0/release_notes.html
https://elephant.readthedocs.io/en/v0.10.0/authors.html

**Comment by herr-zett** [comment]
Added updates 0.8.0, 0.9.0 and 0.10.0 to KG

**Comment by jagru20** [comment]
released.
