### ISSUE TITLE
VisuAlign v0.9

### ISSUE THREAD

**Issue by Majpuc** [bweyers/HBPVisCatalogue#492]
[VisuAlign_Template_openMINDSv2.0.0.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/7986682/VisuAlign_Template_openMINDSv2.0.0.xlsx)

**Comment by jagru20** [comment]
regarding contenttypes: 
+ specific json

**Comment by jagru20** [comment]
https://docs.google.com/spreadsheets/d/1lSIQUjnyHPE2LgorB_z8NSQ22j7Wt1ntSarHUc4jwgY/edit?usp=sharing

**Comment by Majpuc** [comment]
Hi, @jagru20 Do you need more information from me?

**Comment by jagru20** [comment]
is there a reason for not mentioning input types?

**Comment by Majpuc** [comment]
Hi Jan, sorry for overseeing this. I added the input file type now to the form.

**Comment by jagru20** [comment]
Hi Maja, no problem. Thanks for adding it!
