### ISSUE TITLE
Adding BluePyEfe 0.3.90

### ISSUE THREAD

**Issue by wvangeit** [bweyers/HBPVisCatalogue#494]
[BluePyEfe_0_3_90.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/8022730/BluePyEfe_0_3_90.xlsx)

**Comment by jagru20** [comment]
https://docs.google.com/spreadsheets/d/1J2VtoeHAw5bcNLolWZ8q0N-xRRxdxQLQSRM0PG2FKII/edit?usp=sharing

**Comment by jagru20** [comment]
@wvangeit thanks for your curation request. could you please add input and output formats to the information in the [spreadsheet](https://docs.google.com/spreadsheets/d/1J2VtoeHAw5bcNLolWZ8q0N-xRRxdxQLQSRM0PG2FKII/edit?usp=sharing)?
Thank you very much.

Best, 

Jan

**Comment by wvangeit** [comment]
Ok, done

**Comment by jagrue** [comment]
released
