### ISSUE TITLE
NEST Desktop 3.0.0 and 3.1.0

### ISSUE THREAD

**Issue by jens-br** [bweyers/HBPVisCatalogue#496]
Hi all,

NEST Desktop got some more releases in the meantime. Could you add these two versions?

- [ ] [NEST Desktop 3.0.0](https://seafile.rlp.net/f/683911cbbc3f47c2bc89/)
- [ ] [NEST Desktop 3.1.0](https://seafile.rlp.net/f/8f7603f370a346e8b030/)

If you need the patch versions also (in case it is relevant to have a complete dataset), please let me know.

Many thanks in advance!

**Comment by jens-br** [comment]
Are there any updates on this?
If there are any further materials required (additional to the ones linked above), please to not hesitate to contact me!

**Comment by jagru20** [comment]
Released, using the a test run of a new curation approach. thanks for testing!
