### ISSUE TITLE
rgsl_odeiv2

### ISSUE THREAD

**Issue by a-kramer** [bweyers/HBPVisCatalogue#497]
[RGSL_EBRAINS.csv](https://github.com/bweyers/HBPVisCatalogue/files/8191514/RGSL_EBRAINS.csv)

**Comment by jagru20** [comment]
@a-kramer I have reviewed the information on your software and transferred it to a [spreadsheet](https://docs.google.com/spreadsheets/d/1HvwB4OoE_Uzv6ittBaJew7qX2QN4WX5MXAZQmcppVSI/edit?usp=sharing), along with comments. Please have a look and respond to the comments or change the provided information in the spreadsheet accordingly.

**Comment by jagrue** [comment]
released
