### ISSUE TITLE
ImageJ Simple Neurite Tracer 3D user interaction

### ISSUE THREAD

**Issue by flangel3** [bweyers/HBPVisCatalogue#5]
Recherchiere ob es irgendwelche Möglichkeiten gibt das Tool mit alternativen Inputdevices zu bespielen (zum Beispiel eine Space Mouse) oder ob es 3D stereocopic rendering Unterstützung für das Tool gibt. Falls es diese Dinge nicht gibt, wie aufwendig eine Erweiterung wäre.

**Comment by flangel3** [comment]
Habe leider keine Modifikationen gefunden die für ImageJ und Simple Neurite Tracer 3D verfügbar sind. Eventuell könnte ich noch etwas finden wenn ich besser verstehe wie ImageJ und sein Plugin Mechanismus intern funktionieren und wie einfach man da z.b. den Renderer austauschen kann. 

Da alles Open Source ist, wären alternative Inputdevices selbst zu implementieren umsetzbar, aber etwas Zeitaufwendig (vielleicht 10-20 Manntage). Die Darstellung zu ändern wäre nochmal deutlich komplexer.

**Comment by bweyers** [comment]
Die notwendige Anpassung würde Arbeit an dem 3D tracer sowie an ImageJ nach sich ziehen, da standarmäßig 2D Koordinaten für die Interaktion genutzt werden.

**Comment by bweyers** [comment]
Bitte: Zusenden einer kurzen Zusammenfassung per Email an Benni
