### ISSUE TITLE
Remote Connection Manager 1.2

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#50]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1422241403

**Comment by herr-zett** [comment]
The repository on GitHub shows inconsistencies with other information available. For example is the latest release on GitHub tagged as version 0.1.1, whereas this [website](http://www.hpc.cineca.it/software/rcm) states, that the latest version is 1.2. Both versions were supposedly released on 2019-10-17.

It is also suspicious that the GitHub repository is not linked on the homepage of this software.

**Comment by FeldNico** [comment]
> The repository on GitHub shows inconsistencies with other information available. For example is the latest release on GitHub tagged as version 0.1.1, whereas this website states, that the latest version is 1.2. Both versions were supposedly released on 2019-10-17.
> 
> It is also suspicious that the GitHub repository is not linked on the homepage of this software.

We will ask developer soon

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Send to another Developer, as email was invalid

**Comment by FeldNico** [comment]
Developer reminded: 17.03.20

**Comment by bweyers** [comment]
Reminder sent to Robert Mucci

**Comment by bweyers** [comment]
@herr-zett please integrate

**Comment by bweyers** [comment]
Has been released.
