### ISSUE TITLE
MD-IFP

### ISSUE THREAD

**Issue by GiuliaDarrigo** [bweyers/HBPVisCatalogue#502]
[MD-IFP.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/8334563/MD-IFP.xlsx)

**Comment by jagru20** [comment]
https://docs.google.com/spreadsheets/d/1PyKgen9jVRDlLyHlsaSaU6h8ayz0PraVI-EytR7QPWQ/edit#gid=1423678363
