### ISSUE TITLE
PyNN 0.9.5

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#52]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=56975952

**Comment by s4safeld** [comment]
I am finished with gathering data for PyNN

**Comment by s4safeld** [comment]
The IO-formats are unclear. See comments for further explanation

**Comment by FeldNico** [comment]
WIll be send to delevoper soon

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer added feedback in the spreadsheet. Please check and if there are no further questions please integrate.

**Comment by s4safeld** [comment]
I have trouble finding an external database entry for the NMODL language. For now used a link to the documentation of Neuron where it is adressing NMODL.

**Comment by s4safeld** [comment]
I have trouble integrating the file format 'SONATA'. According to the [SONATA documentation](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md) there are several file formats in which the SONATA format can be saved. 
The [PyNN documentation](http://neuralensemble.org/docs/PyNN/import_export.html?#sonata) does not specify which SONATA formats are accepted (I think its json, but I'm not sure). 
Personally I dont think its important to list all the possible formats, so i just listed the three most [common conventions](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md#common-conventions) (hdf5, csv, json).

**Comment by s4safeld** [comment]
Apart from that I am finished integrating PyNN 0.9.5
