### ISSUE TITLE
NeuroM 1.4.16

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#53]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=617431006

**Comment by FeldNico** [comment]
added few notes.
Developer email will be send soon.

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020
