### ISSUE TITLE
Paraver 4.8.2

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#60]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1882267503

**Comment by FeldNico** [comment]
Changed Category: Library -> Application
Feature: Added Time Series Data

Developer email will be send soon

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer reminded: 17.03.20

**Comment by bweyers** [comment]
Please integrate

**Comment by bweyers** [comment]
has been released.
