### ISSUE TITLE
Livre 0.8.0

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#61]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1741331201

**Comment by FeldNico** [comment]
Answered Questions.
 Developer email will be send soon

**Comment by FeldNico** [comment]
Developer email sent: 24.02.2020

**Comment by FeldNico** [comment]
Sent to another developer, as the email was invalid

**Comment by FeldNico** [comment]
Developer reminded: 17.03.20

**Comment by bweyers** [comment]
Please integrate.

**Comment by bweyers** [comment]
Has been released!
