### ISSUE TITLE
BluePyMM 0.6.65

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#62]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=1275549753

**Comment by FeldNico** [comment]
Developer email will be send soon

**Comment by FeldNico** [comment]
Developer-email send: 24.02.2020

**Comment by FeldNico** [comment]
Developer reminded: 16.03.2020

**Comment by bweyers** [comment]
Please integrate.

**Comment by bweyers** [comment]
released
