### ISSUE TITLE
pyJUSBB 0.0.1

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#63]
https://docs.google.com/spreadsheets/d/17xTPVmlqntsAkwiPV-oeBzsJHb-_y1n48TCame-KiSw/edit?usp=sharing

This was brought to our attention by @shahrzadkh. The author is aware of this issue is potentially providing us with informations in the curation process.

Please process this software next.

**Comment by FeldNico** [comment]
- changed typo: CVS -> CSV
- 4D Images = Time Series data
- No CLI or Scripting Interface
(Changes already done by us)

Reminder email will be send soon

**Comment by FeldNico** [comment]
Developer notified: 24.02.2020

**Comment by FeldNico** [comment]
@AnnHa2019 The developer left a few comments. Do we know which format extentions the 2D Plots and the 3D MRI's have?

**Comment by AnnHa2019** [comment]
@FeldNico @bweyers 
I think the MRIs are in nifti format. But for the 2D plots I can't find a format. I have added funder and the nifti format.

**Comment by FeldNico** [comment]
afaik it uses mathplotlib to create images. Therefore the output formats could be:
PNG, PS, EPS, PDF, SVG
