### ISSUE TITLE
Tide 1.5.0

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#65]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=2048047373

**Comment by herr-zett** [comment]
The software was formerly known as "DisplayCluster" (under which name it is listed on Jülichs [HBP-HPC-Platform](https://hbp-hpc-platform.fz-juelich.de/?hbp_software=displaycluster)).
However, this [fork](https://github.com/BlueBrain/DisplayCluster#displaycluster-moved-to-tide) is no longer maintained. Therefore I'm currently working on Tide.
Should DisplayCluster still be integrated?

**Comment by FeldNico** [comment]
> The software was formerly known as "DisplayCluster" (under which name it is listed on Jülichs HBP-HPC-Platform).
> However, this fork is no longer maintained. Therefore I'm currently working on Tide.
> Should DisplayCluster still be integrated?
No

added feature: DIsplay: Tiled Display Wall
Device changed to: Server
(already done by us)

Developer email will be send soon

**Comment by FeldNico** [comment]
Developer email send: 24.02.2020

**Comment by FeldNico** [comment]
Another Developer was contacted, as the current one is no longer developing this software

**Comment by FeldNico** [comment]
Developer reminded: 17.03.20
