### ISSUE TITLE
SpykeViewer 0.4.2

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#66]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=498484968

**Comment by s4safeld** [comment]
I found a Python library named Spyke Utils. It does not depend on Spykeviewer or vice versa. Should I add it to my list? Link to docu: https://spykeutils.readthedocs.io/en/latest/index.html

**Comment by s4safeld** [comment]
I finished SpykeViewer as far as possible. 
The Following things are unclear: 
- I couldn't find information about the copyright. 
- I found two homepages. 
- The Funder is kind of unclear. 
- Is an embedded Python Console a CLI-Feature? 
- The file formats must be confirmed.
Further informations can, as always, be found in the comments

**Comment by s4safeld** [comment]
Update: 
Found Copyright Info

**Comment by FeldNico** [comment]
Notes:
- Copyright Year: Only the first one
- Requirements: python dependencies (requirements.txt) should not be listed

These were already changed by us

Developer email will be send soon

**Comment by FeldNico** [comment]
Developer Email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer sent us feedback. please check and if no further questions integrate.

**Comment by s4safeld** [comment]
The Software Requirements were not taken from the requirements.txt but from [the official documentation](https://spyke-viewer.readthedocs.io/en/latest/installation.html#dependencies).

**Comment by s4safeld** [comment]
Finished integrating SpyViewer 0.4.2
