### ISSUE TITLE
Cube 4.4.4

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#67]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1877130068

**Comment by FeldNico** [comment]
See updated version of "softwarerequirement" description:
https://github.com/bweyers/HBPVisCatalogue/wiki/Attribute-Descriptions
(Already changed by us)

Developer email will be send soon

**Comment by FeldNico** [comment]
Developer Email sent: 24.02.2020

**Comment by FeldNico** [comment]
Developer provided informations. Please check

**Comment by herr-zett** [comment]
Processed developer comments.

Added some new questions.

The developer her-/himself posed a question regarding the data types.

**Comment by FeldNico** [comment]
Answered questions. if no further questions please integrate

**Comment by herr-zett** [comment]
In case of no software requirements needed for a software: Should the corresponding field in the Knowledge Graph be left empty or should "None" be entered?

**Comment by bweyers** [comment]
You may just have a look at other entities hoping to find a similar case. However, I would keep it empty as this may be read as "nothing entered yet" compared to a none which would mean that there aren't which. The latter might not be ultimately the case...

**Comment by herr-zett** [comment]
For this software a [precompiled binary](http://apps.fz-juelich.de/scalasca/releases/cube/4.4/dist/cube-setup.exe) is provided. Considering our Attribute Descriptions this should qualify for the entry "none", shouldn't it? In case we are regarding "none" as a valid entry at all.

**Comment by FeldNico** [comment]
released
