### ISSUE TITLE
SLURM plugin for the co-allocation of compute and data resources v1.0

### ISSUE THREAD

**Issue by bweyers** [bweyers/HBPVisCatalogue#68]
Please check content due to match of the schema, try to look for additional information and start to integrate
[Template.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4193039/Template.xlsx)

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=738742757

**Comment by FeldNico** [comment]
Developer notified: 16.03.20

**Comment by bweyers** [comment]
Please integrate

**Comment by bweyers** [comment]
Has been released.
