### ISSUE TITLE
EBRAINS Knowledge Graph v2.3

### ISSUE THREAD

**Issue by s4safeld** [bweyers/HBPVisCatalogue#69]
https://docs.google.com/spreadsheets/d/1ccoI3KhQehuTtRCG6yjU0IV9qJL9RTU7DZERf6AUPlk/edit#gid=1455957029

**Comment by s4safeld** [comment]
The Knowledge Graph is a [big and complicated net](https://kg.ebrains.eu/kg_components.svg), and the website doesn't really give much [meta information](https://kg.ebrains.eu/deepdive.html) of the KG as a whole. 
I am thinking of implementing the KG just as a software project, and focus on the  [different Components](https://kg.ebrains.eu/kg_components.svg) of the KG, which I will then add to the KG software project in the editor.
But I can imagine how that would overcomplicate the structure of the database and the project.

**Comment by s4safeld** [comment]
Finished the Knowledge Graph as far as possible but there are quite a few things missing due to sparse  and confusing documentations e.g. the programming languages, the copyright, the creation date etc.

**Comment by FeldNico** [comment]
Left a few comments. Discussion on next meeting: View KG from a User or developer site? Please remind if i forget.

**Comment by s4safeld** [comment]
- Added some Developer Comments according to yesterdays discussion. 
- removed faulty Citation link. 
- Proposed another Icon image.
- added "missing" at Copyright info

**Comment by bweyers** [comment]
04-05-20 sent for revision.

**Comment by FeldNico** [comment]
Developer left feedback. Please check&integrate.

**Comment by bweyers** [comment]
has been released, and now it is official that the knowledge graph has been add to the knowledge graph :)
