### ISSUE TITLE
BluePyOpt 1.9.3

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#70]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=738088307

**Comment by FeldNico** [comment]
added few comments

**Comment by bweyers** [comment]
04-05-20 sent for revision

**Comment by FeldNico** [comment]
reminder send.

**Comment by FeldNico** [comment]
Developer left feedback. Please check & integrate

**Comment by bweyers** [comment]
has been released
