### ISSUE TITLE
eFEL 3.0

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#71]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=1854847757

**Comment by FeldNico** [comment]
Could you try to find any other email, as werner Van Geit is already not responding

**Comment by AnnHa2019** [comment]
added other email

**Comment by bweyers** [comment]
Reminder sent.

**Comment by bweyers** [comment]
@AnnHa2019 to be integrated

**Comment by jagru20** [comment]
released
