### ISSUE TITLE
MIP Microservice Infrastructure 4.0.2

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#72]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=843760046

**Comment by FeldNico** [comment]
Diego Abelenda was missing (is listed on the collab site)
Please add emails if possible (already done here)

**Comment by FeldNico** [comment]
Developer notified 16.03.20

**Comment by bweyers** [comment]
Reminder sent.

**Comment by bweyers** [comment]
@AnnHa2019 to be integrated

**Comment by jagru20** [comment]
has been released
