### ISSUE TITLE
Extra-P 3.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#73]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1484438494

Brought to our attention by Prof. Dr. Wolf - TU Darmstadt
Please process this software next.

**Comment by FeldNico** [comment]
Developer added informations. please check and if no further questions please integrate.

**Comment by herr-zett** [comment]
The developer changed the copyright year to 2014-2018. [Here](https://www.scalasca.org/software/extra-p/) it says that the first copyright was registered in 1998.
Which year should be integrated in the KG?

As Components the developer listed CLI and GUI. I guess these have to be listed as Software Features and not Components.

**Comment by bweyers** [comment]
Please use then 2014 as provided by the author.
