### ISSUE TITLE
HiBoP 2.2.3a

### ISSUE THREAD

**Issue by zigaroula** [bweyers/HBPVisCatalogue#74]
https://docs.google.com/spreadsheets/d/1gk9QnvqkAM-oApe2a5UWRRUE86f9NEgLjcaVDbzPVfc/edit#gid=0

**Comment by FeldNico** [comment]
@zigaroula Thanks alot for the meta data! We will curate these and then integrate them.

**Comment by FeldNico** [comment]
@AnnHa2019 Please integrate

**Comment by AnnHa2019** [comment]
To be released, but additions/changes are still necessary. 
I have integrated Unity, DotNetZip, Boost, zlib, OpenCV, NiftiLib as components. This was not planned yet.

**Comment by FeldNico** [comment]
Where did you get these? Imho only NiftiLib should be listed as a component.
@bweyers ?

**Comment by bweyers** [comment]
I agree. Please only add NiftiLib. The rest is standard software or/and not a component.

**Comment by bweyers** [comment]
Released
