### ISSUE TITLE
Extrae 3.7.1

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#75]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=49654767

**Comment by FeldNico** [comment]
Developer notified 16.03.20

**Comment by bweyers** [comment]
Reminder sent.

**Comment by FeldNico** [comment]
Developer left feedback. Please check&integrate.

**Comment by bweyers** [comment]
Has been released
