### ISSUE TITLE
ParaView 5.8.0

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#76]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=2134414627

**Comment by FeldNico** [comment]
answered question. if no further questions please integrate as we can not expect an answer from kitware https://github.com/bweyers/HBPVisCatalogue/issues/18
