### ISSUE TITLE
VTK 8.2.0

### ISSUE THREAD

**Issue by herr-zett** [bweyers/HBPVisCatalogue#77]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1858206265

**Comment by herr-zett** [comment]
Should the version number of the latest release (8.2.0) or the [release candidate](https://vtk.org/download/) (9.0.0) be listed?

**Comment by bweyers** [comment]
Please work with the actual release, not the candidate.

**Comment by FeldNico** [comment]
Please integrate. We already got no answer from Kitware in https://github.com/bweyers/HBPVisCatalogue/issues/18

**Comment by herr-zett** [comment]
There is an already existing instance of VTK in the Knowledge Graph under the name "Visualization Toolkit 8.2.0". The new instance I've created is named "VTK 8.2.0". I guess the old one can be deleted.

**Comment by bweyers** [comment]
Yes please delete!

**Comment by herr-zett** [comment]
Trying to delete the old instance of VTK, I only get an error message

**Comment by FeldNico** [comment]
Can't delete either. Will contact Oli about it

**Comment by bweyers** [comment]
Yes, we have seen this before. @FeldNico please add on the list for Oli!

**Comment by bweyers** [comment]
Released
