### ISSUE TITLE
ChemBioServer 2.0

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#78]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=1378107769

**Comment by FeldNico** [comment]
Will discuss feature with @bweyers

**Comment by bweyers** [comment]
I think that "chemical data type" is not good. We may think about a "Data Type: Abstract Data: Other" category for cases in which we are not able to identfy specific which structural characteristic the data acutally has...

**Comment by AnnHa2019** [comment]
Added comment for the developer

**Comment by bweyers** [comment]
Reminder sent.

**Comment by bweyers** [comment]
Reminder sent

**Comment by FeldNico** [comment]
Developer left feedback. Please integrate

**Comment by bweyers** [comment]
has been released
