### ISSUE TITLE
Develop an SW architecture for editing and creating catalog entries

### ISSUE THREAD

**Issue by bweyers** [bweyers/HBPVisCatalogue#8]
Goal is the develop an architecture for  editing and creating catalog entries using

- a database for handling the XML-based content describing the tools (the catalog entries)
- a web front-end to enter the information by the catalog maintainer

Please create documentation for this on the top page.

**Comment by flangel3** [comment]
- BaseX XML database engine to store catalog entries (basex.org)
- XSD2HTML2XML generates plain HTML5 forms from XML Schemas (XSDs) and transforms filled-in forms into XML (https://github.com/MichielCM/xsd2html2xml)

**Comment by flangel3** [comment]
XSD2HTML2XML provides a XSLT file that transforms an input XSD file into an HTML file with embedded JavaScript code to generate the output XML. The generation of the html file is working, the JavaScript code to transform filled-ins into XML not.

**Comment by flangel3** [comment]
BaseX setup, testing and maintaining with its graphical user interface is finished. BaseX provides a REST interface. I tried to access the database via REST in JavaScript, but got stuck with Cross-Origin Resource Sharing (CORS) problems. BaseX does not support CORS by default and configuration seems to be a bit tricky.
