### ISSUE TITLE
JuGEx 1.0

### ISSUE THREAD

**Issue by bweyers** [bweyers/HBPVisCatalogue#80]
Please check schema and integrate!

[Template_Jugex.xlsx](https://github.com/bweyers/HBPVisCatalogue/files/4318028/Template_Jugex.xlsx)

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1539368360

**Comment by FeldNico** [comment]
Developer notified: 16.03.20

**Comment by bweyers** [comment]
Got feedback from authors and fixed Google sheet according to their comments. Please integrate!

**Comment by bweyers** [comment]
Is released!
