### ISSUE TITLE
PyCOMPSs 2.8

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#89]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=1578553651

**Comment by jagru20** [comment]
This one is outdated, I suggest updating it to the new version (2.8) and sent the resulting changes for revision.

**Comment by herr-zett** [comment]
@jagru20 @bweyers
PyCOMPSs is described as a "Python Binding for COMP Superscalar (COMPSs) Runtime" and doesn't really have a documentation of its own. Both, the [official website](https://www.bsc.es/research-and-development/software-and-apps/software-list/comp-superscalar/) as well as [documentation](https://compss-doc.readthedocs.io/en/stable/) linked in the [PyCOMPs project description](https://pypi.org/project/pycompss/2.8/#description) refer to COMPs in general.

Should therefore the whole spreadsheet be adapted to suit COMPs?

**Comment by jagru20** [comment]
Dear @bsc-wdc,

we are about to transfer your software *PyCOMPSs* from the HBP Collaboratory Software Catalogue into the new [EBRAINS knowledge graph](https://search.kg.ebrains.eu/?facet_type[0]=Software). We noticed, that *PyCOMPSs* is a part of COMPSs and wondered, if you want only PyCOMPSs to be available in the KG or also (maybe only) COMPSs. Could you please give us quick feedback on this?

Thanks!

Software Meta Data Curation Team

**Comment by jagru20** [comment]
@herr-zett Developer left feedback. Please check and integrate as PyCOMPSs. The developer wants PyCOMPSs and COMPSs integrated seperately.

**Comment by herr-zett** [comment]
@jagru20 @bweyers In the new KG the field "Full Documentation" has to be filled with a file or DOI. Is a URL (in this case [this one](https://pycompss.readthedocs.io/en/2.8/index.html)) no longer allowed?

**Comment by jagru20** [comment]
Thanks for pointing this out. There are discussions ongoing on how to cope with this. For now please integrate without the docs, we will have to recurate that later.

**Comment by jagru20** [comment]
> @jagru20 @bweyers In the new KG the field "Full Documentation" has to be filled with a file or DOI. Is a URL (in this case [this one](https://pycompss.readthedocs.io/en/2.8/index.html)) no longer allowed?

Links are working again. I added the respective link to the KG entry.

**Comment by jagru20** [comment]
released!
