### ISSUE TITLE
GABAergic cell fractions per Layer Validation 22.10.2015

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#91]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=1056194986

**Comment by herr-zett** [comment]
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=265310284

**Comment by FeldNico** [comment]
Task from the Collaboratory should not be integrated.
