### ISSUE TITLE
HBP Bootstrap Theme 0.1.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#92]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=1329658278

**Comment by s4safeld** [comment]
The spreadsheet states that its in version 0.0.17.
But the given [documentation](https://collab.humanbrainproject.eu/#/collab/54/nav/1875) is about 0.0.18 and the given [github repository](https://github.com/HumanBrainProject/hbp-collaboratory-theme/releases) is in release 1.0.0. Which version should i work on? In my opinion it should be the latest (1.0.0)

**Comment by s4safeld** [comment]
I am finished completing the spreadsheet as far as possible. For now I focused on version 0.0.17, but I expect to update the spreadsheet to 0.1.0 before integrating. Nonetheless I am going to set the label for this software to "in curation".

**Comment by FeldNico** [comment]
Please update to 1.0.0 as much as possible. The developer should then decide.

**Comment by s4safeld** [comment]
- updated spreadsheet to 0.1.0
- changed the spreadsheets name to 0.1.0
- changed this issues name to 0.1.0

**Comment by jagru20** [comment]
reminder sent

**Comment by jagru20** [comment]
The developer does not react to our request for revision. The issue is closed and not integrated, as the description is not sufficient. The issue may be reopened on demand.
