### ISSUE TITLE
Intrinsic+Extrinsic Synapse Densities Per Layer Validation 22.10.2015

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#95]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=474331601

**Comment by s4safeld** [comment]
I could not find this software. The given link to the source code is 404. And after some searching, the best I could find is [this official HBP document](https://sos-ch-dk-2.exo.io/public-website-production/filer_public/a4/8b/a48b18aa-fd29-4f36-8b8b-d54c1abd7dd1/d673_rup_m18_accepted_20160803.pdf) where figure 20 inherits a screenshot of a software which has a very similar name to this one. But the links given on this document are either forbidden or lead to an empty page. For now I will move on to the next software project.

**Comment by bweyers** [comment]
In this case, we are not considering this software any furhter!

**Comment by FeldNico** [comment]
Task from the Collaboratory should not be integrated.
