### ISSUE TITLE
microcircuit_task 22.10.2015

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#98]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=1386161211

**Comment by s4safeld** [comment]
I finished this software as far as possible. But it is so unique that almost every point is worth a discussion.

**Comment by FeldNico** [comment]
Will discuss with @bweyers how we handle tasks

**Comment by bweyers** [comment]
Tasks represent software from a pre-SGA1 era and are not used any more. Will be deleted in a next automatic update...

**Comment by FeldNico** [comment]
Task from the Collaboratory should not be integrated.
